import React from "react";
import LegalPage from "./LegalPage";
import {
	ShieldCheck,
	Lock,
	Eye,
	Share2,
	Database,
	UserCircle,
	Cookie,
	Mail,
	Globe,
	Activity
} from "lucide-react";

const CONTACT_EMAIL = "support@toletpro.rent";

const POLICY_SECTIONS = [
	{
		id: "introduction",
		icon: <ShieldCheck className="w-5 h-5" />,
		titleEn: "1. Introduction & Interpretation",
		titleBn: "১. পরিচিতি এবং ব্যাখ্যা",
		contentEn: `Welcome to TO-LET PRO. This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.`,
		contentBn: `TO-LET PRO-তে আপনাকে স্বাগতম। আপনি যখন আমাদের সেবা ব্যবহার করেন তখন আমরা কীভাবে আপনার তথ্য সংগ্রহ, ব্যবহার এবং প্রকাশ করি তা এই নীতিতে বর্ণনা করা হয়েছে। আমাদের সেবা ব্যবহার করার মাধ্যমে আপনি এই গোপনীয়তা নীতির সাথে সম্মত হচ্ছেন।`
	},
	{
		id: "definitions",
		icon: <Globe className="w-5 h-5" />,
		titleEn: "2. Definitions",
		titleBn: "২. সংজ্ঞাসমূহ",
		contentEn: `For the purposes of this Privacy Policy:
- **Account**: means a unique account created for You to access our Service.
- **Company**: (referred to as "We", "Us" or "Our") refers to TO-LET PRO, Bangladesh.
- **Cookies**: are small files placed on Your device by a website containing browsing history details.
- **Device**: means any device that can access the Service such as a computer, a cellphone or a digital tablet.
- **Personal Data**: is any information that relates to an identified or identifiable individual.
- **Service**: refers to the Website and our Mobile Application.
- **Usage Data**: refers to data collected automatically, generated by the use of the Service.`,
		contentBn: `এই নীতির উদ্দেশ্যে:
- **অ্যাকাউন্ট**: আমাদের সেবা অ্যাক্সেস করার জন্য আপনার নামে তৈরি একটি ইউনিক অ্যাকাউন্ট।
- **কোম্পানি**: "আমরা" বা "আমাদের" বলতে TO-LET PRO, বাংলাদেশ-কে বোঝানো হয়েছে।
- **কুকিজ**: ছোট ফাইল যা আপনার ডিভাইসে ব্রাউজিং হিস্ট্রি সংরক্ষণ করে।
- **ডিভাইস**: কম্পিউটার, মোবাইল বা ট্যাবলেট যার মাধ্যমে আপনি আমাদের সেবা গ্রহণ করেন।
- **ব্যক্তিগত ডেটা**: যেকোনো তথ্য যা কোনো নির্দিষ্ট ব্যক্তিকে চিহ্নিত করতে পারে।`
	},
	{
		id: "information-collection",
		icon: <Database className="w-5 h-5" />,
		titleEn: "3. Information We Collect",
		titleBn: "৩. আমরা যে তথ্য সংগ্রহ করি",
		contentEn: `While using Our Service, We may ask You to provide Us with certain personally identifiable information:
- **Personal Data**: Phone number, First name and last name, Email address, Address, National ID (NID) for verification, and Profession details.
- **Usage Data**: Collected automatically (e.g., IP address, browser type, pages visited, time spent on pages, unique device identifiers).
- **Location Data**: We collect location data to help you find nearby properties and optimize rent alerts.
- **Information from Third-Party Services**: If you register via Google or Facebook, we collect data associated with that account.`,
		contentBn: `আমাদের সেবা ব্যবহার করার সময়, আমরা আপনার ব্যক্তিগত তথ্য সংগ্রহ করতে পারি:
- **ব্যক্তিগত ডেটা**: ফোন নম্বর, নাম, ইমেইল, ঠিকানা, এনআইডি (NID), এবং পেশার বিবরণ।
- **ব্যবহারের ডেটা**: আপনার আইপি অ্যাড্রেস, ব্রাউজারের ধরন, পরিদর্শনের সময় ইত্যাদি স্বয়ংক্রিয়ভাবে সংগৃহীত হয়।
- **লোকেশন ডেটা**: আশেপাশের প্রপার্টি খুঁজতে আমরা লোকেশন ডেটা ব্যবহার করি।`
	},
	{
		id: "use-of-data",
		icon: <Activity className="w-5 h-5" />,
		titleEn: "4. Use of Your Personal Data",
		titleBn: "৪. ব্যক্তিগত তথ্যের ব্যবহার",
		contentEn: `The Company may use Personal Data for the following purposes:
- **To provide and maintain our Service**: Including monitoring the usage of our Service.
- **To manage Your Account**: Managing Your registration as a user of the Service.
- **For the performance of a contract**: Compliance and undertaking of the lease/booking contracts.
- **To contact You**: By email, telephone calls, SMS, or push notifications regarding updates or security.
- **To manage Your requests**: To attend and manage Your inquiries or support tickets.
- **For business transfers**: Evaluating or conducting a merger, restructuring, or sale of assets.`,
		contentBn: `আমরা নিম্নলিখিত উদ্দেশ্যে আপনার ব্যক্তিগত ডেটা ব্যবহার করতে পারি:
- **সেবা প্রদান এবং রক্ষণাবেক্ষণ**: সেবার ব্যবহার পর্যবেক্ষণ করা।
- **অ্যাকাউন্ট পরিচালনা**: আপনার রেজিস্ট্রেশন এবং প্রোফাইল পরিচালনা করা।
- **চুক্তির বাস্তবায়ন**: বুকিং বা ভাড়ার চুক্তির শর্তাবলি পূরণ করা।
- **যোগাযোগ**: আপডেট বা সিকিউরিটি সম্পর্কে ইমেইল, কল বা এসএমএস এর মাধ্যমে যোগাযোগ করা।`
	},
	{
		id: "sharing-disclosure",
		icon: <Share2 className="w-5 h-5" />,
		titleEn: "5. Sharing and Disclosure",
		titleBn: "৫. ডেটা শেয়ারিং এবং প্রকাশ",
		contentEn: `We may share Your personal information in the following situations:
- **With Service Providers**: To monitor and analyze the use of our Service, process payments, or verify identity.
- **With Law Enforcement**: Under certain circumstances, We may disclose Your Personal Data if required by law or public authorities.
- **With Other Users**: Your public profile name, verified status, and interactions (like reviews or inquiries) are visible to related landlords/tenants.
- **With Your consent**: We may disclose Your personal information for any other purpose with Your explicit consent.`,
		contentBn: `আমরা নিচের পরিস্থিতিতে আপনার তথ্য শেয়ার করতে পারি:
- **সেবা প্রদানকারীদের সাথে**: পেমেন্ট প্রসেসিং বা আইডেন্টিটি ভেরিফিকেশনের জন্য।
- **আইন প্রয়োগকারী সংস্থার সাথে**: আইনি প্রয়োজনে বা সরকারি কর্তৃপক্ষের বৈধ অনুরোধে।
- **অন্যান্য ব্যবহারকারীদের সাথে**: আপনার প্রোফাইল এবং ভেরিফাইড স্ট্যাটাস অন্য বাড়িওয়ালা বা ভাড়াটিয়া দেখতে পারবেন।`
	},
	{
		id: "retention-transfer",
		icon: <Eye className="w-5 h-5" />,
		titleEn: "6. Retention & Transfer of Data",
		titleBn: "৬. ডেটা সংরক্ষণ এবং স্থানান্তর",
		contentEn: `**Retention**: The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy, to comply with our legal obligations, resolve disputes, and enforce our legal agreements.
**Transfer**: Your information is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It may be transferred to computers located outside of Your jurisdiction where data protection laws may differ.`,
		contentBn: `**সংরক্ষণ**: আমরা আপনার ব্যক্তিগত ডেটা কেবল আইনি বাধ্যবাধকতা, বিরোধ নিষ্পত্তি এবং চুক্তির শর্ত পূরণের জন্য যতটুকু সময় প্রয়োজন, ততটুকুই সংরক্ষণ করব।
**স্থানান্তর**: আপনার তথ্য আমাদের সার্ভারে এবং প্রক্রিয়াজাতকরণে জড়িত অন্যান্য স্থানে স্থানান্তরিত হতে পারে।`
	},
	{
		id: "data-deletion",
		icon: <UserCircle className="w-5 h-5" />,
		titleEn: "7. Data Deletion / Unsubscribe",
		titleBn: "৭. ডেটা মুছে ফেলা / আনসাবস্ক্রাইব",
		contentEn: `If at any time you wish to have your information reviewed, modified, or permanently removed from our active databases, you have the right to request Data Deletion. 
Please contact us at **${CONTACT_EMAIL}** with the subject "Data Deletion Request" and include your registered phone number/email. We may contact you to confirm your identity before wiping your data. You can also delete your account directly from the App Settings under "Privacy Center".`,
		contentBn: `আপনি চাইলে যেকোনো সময় আমাদের ডাটাবেস থেকে আপনার ব্যক্তিগত তথ্য মুছে ফেলার অনুরোধ করতে পারেন।
আপনার ডেটা ডিলিট করতে অ্যাপের সেটিংস থেকে "Privacy Center" ব্যবহার করুন অথবা **${CONTACT_EMAIL}** এ "Data Deletion Request" লিখে ইমেইল করুন।`
	},
	{
		id: "data-security",
		icon: <Lock className="w-5 h-5" />,
		titleEn: "8. Security of Your Personal Data",
		titleBn: "৮. আপনার তথ্যের নিরাপত্তা",
		contentEn: `The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means (such as SSL encryption and Firebase secure rules) to protect Your Personal Data, We cannot guarantee its absolute security.`,
		contentBn: `আপনার তথ্যের নিরাপত্তা আমাদের কাছে অত্যন্ত গুরুত্বপূর্ণ। আমরা এসএসএল (SSL) এনক্রিপশন এবং নিরাপদ ডেটাবেস ব্যবহার করি, তবে ইন্টারনেটে কোনো পদ্ধতিই ১০০% নিরাপদ নয়।`
	},
	{
		id: "childrens-privacy",
		icon: <Cookie className="w-5 h-5" />,
		titleEn: "9. Children's Privacy",
		titleBn: "৯. শিশুদের গোপনীয়তা",
		contentEn: `Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected data from minors without parental consent, We will take steps to remove that information.`,
		contentBn: `আমাদের প্ল্যাটফর্ম ১৩ বছরের কম বয়সীদের জন্য নয়। আমরা জেনেশুনে শিশুদের কোনো ব্যক্তিগত তথ্য সংগ্রহ করি উল্লেখযোগ্য নয়। যদি আমরা জানতে পারি যে অনুমতি ছাড়া কোনো তথ্য সংগ্রহ করা হয়েছে, তবে তা মুছে ফেলা হবে।`
	},
	{
		id: "contact",
		icon: <Mail className="w-5 h-5" />,
		titleEn: "10. Contact Us",
		titleBn: "১০. যোগাযোগ করুন",
		contentEn: `If you have any questions about this Privacy Policy, please contact us by email at ${CONTACT_EMAIL}.`,
		contentBn: `এই গোপনীয়তা নীতি সম্পর্কে আপনার কোনো প্রশ্ন থাকলে, অনুগ্রহ করে ইমেইলের মাধ্যমে আমাদের সাথে যোগাযোগ করুন: ${CONTACT_EMAIL}`
	}
];

export default function PrivacyPolicy() {
	return (
		<LegalPage 
			titleEn="Privacy Policy"
			titleBn="গোপনীয়তা নীতি"
			lastUpdated="August 2026"
			sections={POLICY_SECTIONS}
			headerIcon={ShieldCheck}
		/>
	);
}
