/**
 * listingCounts.js — GENERATED FILE, DO NOT EDIT BY HAND.
 * ─────────────────────────────────────────────────────────────────────────────
 * Regenerate with:  npm run seo:counts   (runs automatically on every build)
 * Source: scripts/fetch-listing-counts.mjs, which asks the live API.
 *
 * path → number of live listings on that location page, as of the last build.
 *
 * `ok: false` means the API could not be reached and the numbers below are not
 * trustworthy; every consumer must then behave as it did before this file
 * existed and include every page.
 */

export const LISTING_COUNTS_OK = true;
export const LISTING_COUNTS_FETCHED_AT = "2026-08-29T22:21:55.056Z";
export const LISTING_COUNTS = {
 "/properties/dhaka": 15,
 "/properties/chittagong": 0,
 "/properties/sylhet": 0,
 "/properties/rajshahi": 0,
 "/properties/khulna": 0,
 "/properties/barishal": 0,
 "/properties/rangpur": 0,
 "/properties/mymensingh": 0,
 "/properties/faridpur": 0,
 "/properties/gazipur": 0,
 "/properties/gopalganj": 0,
 "/properties/kishoreganj": 0,
 "/properties/madaripur": 0,
 "/properties/manikganj": 0,
 "/properties/munshiganj": 0,
 "/properties/narayanganj": 0,
 "/properties/narsingdi": 0,
 "/properties/rajbari": 0,
 "/properties/shariatpur": 0,
 "/properties/tangail": 0,
 "/properties/bandarban": 0,
 "/properties/brahmanbaria": 0,
 "/properties/chandpur": 0,
 "/properties/chattogram": 0,
 "/properties/comilla": 0,
 "/properties/cox-bazar": 0,
 "/properties/feni": 0,
 "/properties/khagrachari": 0,
 "/properties/lakshmipur": 0,
 "/properties/noakhali": 0,
 "/properties/rangamati": 0,
 "/properties/habiganj": 0,
 "/properties/moulvibazar": 0,
 "/properties/sunamganj": 0,
 "/properties/bogura": 0,
 "/properties/chapainawabganj": 0,
 "/properties/joypurhat": 0,
 "/properties/naogaon": 0,
 "/properties/natore": 0,
 "/properties/pabna": 0,
 "/properties/sirajganj": 0,
 "/properties/bagerhat": 0,
 "/properties/chuadanga": 0,
 "/properties/jashore": 0,
 "/properties/jhenaidah": 0,
 "/properties/kushtia": 0,
 "/properties/magura": 0,
 "/properties/meherpur": 0,
 "/properties/narail": 0,
 "/properties/satkhira": 0,
 "/properties/barguna": 0,
 "/properties/bhola": 0,
 "/properties/jhalokati": 0,
 "/properties/patuakhali": 0,
 "/properties/pirojpur": 0,
 "/properties/dinajpur": 0,
 "/properties/gaibandha": 0,
 "/properties/kurigram": 0,
 "/properties/lalmonirhat": 0,
 "/properties/nilphamari": 0,
 "/properties/panchagarh": 0,
 "/properties/thakurgaon": 0,
 "/properties/jamalpur": 0,
 "/properties/netrokona": 0,
 "/properties/sherpur": 0,
 "/properties/adabar-dhaka": 0,
 "/properties/aftab-nagar-dhaka": 0,
 "/properties/airport-dhaka": 0,
 "/properties/ashulia-dhaka": 1,
 "/properties/azimpur-dhaka": 0,
 "/properties/badda-dhaka": 0,
 "/properties/bailey-road-dhaka": 0,
 "/properties/banani-dhaka": 1,
 "/properties/banasree-dhaka": 0,
 "/properties/bangshal-dhaka": 0,
 "/properties/baridhara-dhaka": 0,
 "/properties/bashabo-dhaka": 0,
 "/properties/bashundhara-r-a-dhaka": 0,
 "/properties/bhashantek-dhaka": 0,
 "/properties/bhatara-dhaka": 0,
 "/properties/cantonment-dhaka": 0,
 "/properties/chawkbazar-dhaka": 0,
 "/properties/dakshinkhan-dhaka": 0,
 "/properties/darus-salam-dhaka": 0,
 "/properties/dattapara-dhaka": 8,
 "/properties/demra-dhaka": 0,
 "/properties/dhamrai-dhaka": 0,
 "/properties/dhanmondi-dhaka": 1,
 "/properties/dhanmondi-1-dhaka": 1,
 "/properties/dhanmondi-10-dhaka": 0,
 "/properties/dhanmondi-11-dhaka": 0,
 "/properties/dhanmondi-12-dhaka": 0,
 "/properties/dhanmondi-13-dhaka": 0,
 "/properties/dhanmondi-14-dhaka": 0,
 "/properties/dhanmondi-15-dhaka": 0,
 "/properties/dhanmondi-2-dhaka": 1,
 "/properties/dhanmondi-27-dhaka": 0,
 "/properties/dhanmondi-3-dhaka": 0,
 "/properties/dhanmondi-32-dhaka": 0,
 "/properties/dhanmondi-4-dhaka": 1,
 "/properties/dhanmondi-5-dhaka": 0,
 "/properties/dhanmondi-6-dhaka": 0,
 "/properties/dhanmondi-7-dhaka": 1,
 "/properties/dhanmondi-8-dhaka": 1,
 "/properties/dhanmondi-9a-dhaka": 1,
 "/properties/dohar-dhaka": 0,
 "/properties/eskaton-dhaka": 0,
 "/properties/farmgate-dhaka": 0,
 "/properties/gendaria-dhaka": 0,
 "/properties/gulshan-dhaka": 0,
 "/properties/gulshan-1-dhaka": 0,
 "/properties/gulshan-2-dhaka": 0,
 "/properties/hatirjheel-dhaka": 0,
 "/properties/hazaribagh-dhaka": 0,
 "/properties/hemayetpur-dhaka": 0,
 "/properties/jatrabari-dhaka": 0,
 "/properties/jigatola-dhaka": 0,
 "/properties/kadamtali-dhaka": 0,
 "/properties/kafrul-dhaka": 0,
 "/properties/kalabagan-dhaka": 0,
 "/properties/kamrangirchar-dhaka": 0,
 "/properties/karwan-bazar-dhaka": 0,
 "/properties/kazipara-dhaka": 0,
 "/properties/keraniganj-dhaka": 0,
 "/properties/khilgaon-dhaka": 0,
 "/properties/khilkhet-dhaka": 0,
 "/properties/kotwali-dhaka": 0,
 "/properties/lalbagh-dhaka": 0,
 "/properties/lalmatia-dhaka": 1,
 "/properties/malibagh-dhaka": 0,
 "/properties/maniknagar-dhaka": 0,
 "/properties/merul-badda-dhaka": 0,
 "/properties/mirpur-dhaka": 1,
 "/properties/mirpur-1-dhaka": 1,
 "/properties/mirpur-10-dhaka": 0,
 "/properties/mirpur-11-dhaka": 0,
 "/properties/mirpur-12-dhaka": 0,
 "/properties/mirpur-13-dhaka": 0,
 "/properties/mirpur-14-dhaka": 0,
 "/properties/mirpur-2-dhaka": 1,
 "/properties/mirpur-6-dhaka": 0,
 "/properties/mirpur-dohs-dhaka": 0,
 "/properties/mohakhali-dhaka": 1,
 "/properties/mohakhali-dohs-dhaka": 0,
 "/properties/mohammadpur-dhaka": 1,
 "/properties/motijheel-dhaka": 0,
 "/properties/mouchak-dhaka": 0,
 "/properties/mugda-dhaka": 0,
 "/properties/nawabganj-dhaka": 0,
 "/properties/new-market-dhaka": 0,
 "/properties/niketan-dhaka": 0,
 "/properties/nikunja-1-dhaka": 0,
 "/properties/nikunja-2-dhaka": 0,
 "/properties/nilkhet-dhaka": 0,
 "/properties/north-badda-dhaka": 0,
 "/properties/old-dhaka-dhaka": 0,
 "/properties/pallabi-dhaka": 0,
 "/properties/paltan-dhaka": 0,
 "/properties/ramna-dhaka": 0,
 "/properties/rampura-dhaka": 0,
 "/properties/rayer-bazar-dhaka": 0,
 "/properties/rupnagar-dhaka": 0,
 "/properties/sabujbagh-dhaka": 0,
 "/properties/savar-dhaka": 8,
 "/properties/segunbagicha-dhaka": 0,
 "/properties/shah-ali-dhaka": 0,
 "/properties/shahbagh-dhaka": 0,
 "/properties/shahjahanpur-dhaka": 0,
 "/properties/shantinagar-dhaka": 0,
 "/properties/sher-e-bangla-nagar-dhaka": 0,
 "/properties/shewrapara-dhaka": 0,
 "/properties/shyamoli-dhaka": 0,
 "/properties/shyampur-dhaka": 0,
 "/properties/sutrapur-dhaka": 0,
 "/properties/tejgaon-dhaka": 0,
 "/properties/tejgaon-i-a-dhaka": 0,
 "/properties/tejgaon-industrial-area-dhaka": 0,
 "/properties/turag-dhaka": 0,
 "/properties/uttara-east-dhaka": 0,
 "/properties/uttara-sector-1-dhaka": 1,
 "/properties/uttara-sector-10-dhaka": 0,
 "/properties/uttara-sector-11-dhaka": 0,
 "/properties/uttara-sector-12-dhaka": 1,
 "/properties/uttara-sector-13-dhaka": 0,
 "/properties/uttara-sector-14-dhaka": 0,
 "/properties/uttara-sector-18-dhaka": 0,
 "/properties/uttara-sector-3-dhaka": 1,
 "/properties/uttara-sector-4-dhaka": 0,
 "/properties/uttara-sector-6-dhaka": 0,
 "/properties/uttara-sector-7-dhaka": 0,
 "/properties/uttara-sector-9-dhaka": 0,
 "/properties/uttara-west-dhaka": 0,
 "/properties/uttarkhan-dhaka": 0,
 "/properties/wari-dhaka": 0
};

/**
 * Should this location page be offered to search engines?
 * Unknown counts and a failed fetch both mean "yes" — fail open, never hide a
 * page because of a network problem.
 */
export const hasListings = (path) => {
  if (!LISTING_COUNTS_OK) return true;
  const n = LISTING_COUNTS[path];
  return n === undefined ? true : n > 0;
};
