import React, { createContext, useState, useContext, useEffect } from 'react';

// Storage key used to persist the user's language preference across reloads.
const LANG_STORAGE_KEY = 'tolet_lang';

// Bengali is the primary default — most TO-LET PRO users are Bangladeshi.
// Anyone who explicitly toggles to English still has their choice honoured
// because we save it to localStorage below.
const DEFAULT_LANGUAGE = 'বাংলা';

const readInitialLanguage = () => {
  if (typeof window === 'undefined') return DEFAULT_LANGUAGE;
  try {
    const stored = window.localStorage.getItem(LANG_STORAGE_KEY);
    if (stored === 'English' || stored === 'বাংলা') return stored;
  } catch {
    /* localStorage blocked (e.g. SSR / private mode) → fall through */
  }
  return DEFAULT_LANGUAGE;
};

const translations = {
  'English': {
    // Navbar & Hero
    brand: "TO-LET PRO", 
    business: "Business", 
    listProperty: "List Property", 
    login: "Login / Signup", 
    allCities: "ALL CITIES",
    findYourNext: "Find your next", 
    sweetHome: "Sweet Home",

    // Hero Section
    heroTagline: "Bangladesh's #1 Property Platform",
    heroTitle1: "Find Your Next",
    heroTitle2: "Perfect Home",
    heroSubtext: "Discover premium apartments, duplexes, and commercial spaces across Bangladesh with 100% verified hosts.",
    tabRent: "Rent",
    tabBuy: "Buy",
    tabCommercial: "Commercial",
    searchLocation: "Location",
    locationPlaceholder: "Where do you want to live?",
    searchType: "Property Type",
    searchBudget: "Budget Range",
    searchBtn: "Search",
    typeAny: "Any Property",
    typeApt: "Apartment",
    typeDuplex: "Duplex",
    typeStudio: "Studio",
    budgetAny: "Choose Range",
    budgetLow: "Below 20k",
    budgetMid: "20k - 50k",
    budgetHigh: "50k - 100k",
    budgetPremium: "Above 100k",
    
    // Browse By Location Section
    premiumLocations: "Premium Locations",
    browseBy: "Browse by",
    locationText: "Location",
    viewFeatured: "View Featured",
    viewAllCities: "View All Cities",
    listings: "Listings",

    // Popular Locations Section 
    primeLocations: "Prime Locations",
    dhakasFinest: "Dhaka's Finest",
    districts: "Districts",
    districtsDesc: "Premium urban hubs, curated for the modern professional and family living.",
    viewAllNeighborhoods: "View all neighborhoods",
    viewLess: "View less",
    premiumListings: "Premium Listings",
    
    // Uttara Banner
    uttaraSectors: "Uttara Sectors",
    uttaraDesc: "Unique residential sectors with planned layouts, excellent connectivity to the airport and upcoming metro rail.",
    exploreSectorListings: "Explore Sector Listings",
    
   // Stats Section
   dhakaCentral: "Dhaka Central",
   sylhetHills: "Sylhet Hills",
   chittagongPort: "Chittagong Port",
   nationwideNetwork: "Nationwide Network",
   statsTitle1: "There's a TO-LET",
   statsTitleAround: "around.",
   statsTitleAlways: "Always.",
   statsDesc: "Nationwide availability. Unmatched scale. Whether it's a bustling urban flat or a serene suburban villa, we have the keys.",
   districtsCovered: "Districts Covered",
   activeListings: "Active Listings",
   divisionText: "Division",

    // CTA Section
    joinFuture: "Join the Future of Renting",
    readyToList: "Ready to list your",
    spaceText: "space?",
    ctaDesc: "Join over 5,000 trusted hosts who have already found their perfect tenants through Bangladesh's most premium rental platform.",
    getStartedFree: "Get Started for Free",
    learnMoreBtn: "Learn More",

    // Footer Section
    footerDesc: "Elevating the rental experience in Bangladesh through curated premium listings and seamless modern technology.",
    discoveryTitle: "Discovery",
    navNewListings: "New Listings",
    navPopularAreas: "Popular Areas",
    navAffordableStudios: "Affordable Studios",
    navLuxuryFlats: "Luxury Flats",
    landlordsTitle: "For Landlords",
    navHowItWorks: "How it Works",
    navListProperty: "List a Property",
    navTrustSafety: "Trust & Safety",
    navHostGuidelines: "Host Guidelines",
    stayInspired: "Stay Inspired",
    newsletterDesc: "Join our newsletter for curated home recommendations.",
    emailPlaceholder: "Your email",
    footerCopyright: "© 2026 TO-LET PRO. ALL RIGHTS RESERVED.",
    privacyPolicyUpper: "PRIVACY POLICY",
    termsServiceUpper: "TERMS OF SERVICE",
    cookiesUpper: "COOKIES",

    // Filters & Property Listing
    activeFilters: "Active Filters",
    clearAll: "CLEAR ALL",
    sortNewest: "Newest Listings",
    sortPriceLowHigh: "Price Low → High",
    sortPriceHighLow: "Price High → Low",
    sortPopular: "Most Popular",
    filtersBtn: "Filters",
    advancedFilter: "Advanced",
    filterWord: "Filter",
    searchAreaPlaceholder: "Search area...",
    nearMe: "Near Me",
    locating: "Locating",
    filterPrice: "Price Range",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    filterPropType: "Property Type",
    propApartment: "Apartment",
    propIndependent: "Independent House",
    propDuplex: "Duplex",
    propStudio: "Studio",
    propPenthouse: "Penthouse",
    filterRooms: "Bedrooms & Bathrooms",
    bedrooms: "Bedrooms",
    bathroomType: "Bathroom Type",
    any: "Any",
    attachedBath: "Attached",
    sharedBath: "Shared",
    filterSize: "Size (Area Sqft)",
    maxSize: "Max Size:",
    filterUtilities: "Utilities Included",
    waterBill: "Water Bill",
    electricityBill: "Electricity Bill",
    gasSupply: "Gas Supply",
    internetWifi: "Internet/WiFi",
    serviceCharge: "Service Charge",
    filterTenant: "Who's moving in",
    tenantType: "Who's moving in?",
    family: "Family",
    bachelor: "Bachelor",
    students: "Students",
    petsAllowed: "Pets allowed",
    // Rental category labels (shared by chip group on the listing page)
    filterWhoMovesIn: "Who's moving in?",
    catFamilyFlat: "Family Flat",
    catBachelorMale: "Bachelor (Male)",
    catBachelorFemale: "Bachelor (Female)",
    catSubletRoom: "Sublet / Room",
    catStudent: "Student",
    // Quick budget pills shown above the price slider
    quickBudgetLabel: "Quick budget",
    budgetUpto15k: "Under ৳15k",
    budgetUpto25k: "৳15k–৳25k",
    budgetUpto40k: "৳25k–৳40k",
    budgetUpto60k: "৳40k–৳60k",
    budgetAbove60k: "Above ৳60k",
    furnishing: "Furnishing",
    furnished: "Furnished",
    semiFurnished: "Semi-Furnished",
    unfurnished: "Unfurnished",
    filterAmenities: "Amenities & Floor",
    amenities: "Amenities",
    parking: "Parking",
    elevator: "Elevator",
    generator: "Generator",
    securityCctv: "Security/CCTV",
    ac: "AC",
    floorLevel: "Floor Level",
    anyFloor: "Any Floor",
    groundFloor: "Ground Floor",
    floor1to3: "1st to 3rd Floor",
    floor4to7: "4–7 Floor",
    floor8Plus: "8+ Floor",
    filterFinancials: "Deposit & Availability",
    depositAdvance: "Deposit / Advance",
    noAdvance: "No Advance",
    monthAdvance1: "1 Month Advance",
    monthAdvance2: "2 Months Advance",
    negotiableDeposit: "Negotiable Deposit",
    availability: "Availability",
    availableNow: "Available Now",
    availableThisMonth: "Available This Month",
    availableNextMonth: "Available Next Month",
    filterRating: "Property Rating",
    star4Above: "4★ & Above",
    star3Above: "3★ & Above",
    anyRating: "Any Rating",
    applyFiltersBtn: "Apply Filters",
    showing: "Showing",
    backToTop: "Back to Top",
    home: "Home",
    sortBy: "Sort by:",
    reviews: "Reviews",
    inquiriesToday: "Inquiries Today",
    off: "Off",
    perMonthExcluding: "Per Month • Excluding Utilities",
    detailsBtn: "Details",
    clearFilters: "Clear Filters",
    searchWithin: "Search within",

    // Property Card & Details
    properties: "Properties",
    verified: "VERIFIED",
    monthlyRentText: "Monthly Rent",
    inquireBtn: "INQUIRE",
    beds: "Beds",
    baths: "Baths",
    sqft: "sqft",
    noPropsFound: "No properties found",
    noPropsDesc: "We couldn't find any listings for",
    adjustFilters: "Try adjusting your filters.",
    bangladesh: "Bangladesh",
    backToResults: "Back to Search",
    aboutProperty: "About this property",
    propertyDesc: "Experience unparalleled luxury in the heart of the city.",
    amenitiesTitle: "Amenities",
    propDetailsTitle: "Property Details",
    listedBy: "LISTED BY",
    viewProfile: "View Profile",
    callNow: "Call Now",
    messageBtn: "Message",
    requestDetails: "Request Details",
    yourName: "Your Name",
    phoneNum: "Phone Number",
    messageLabel: "Message",
    defaultMsg: "I am interested in this property.",
    submitInquiry: "Submit Inquiry",
    share: "Share",
    save: "Save",
    availableImmed: "Available Immediately",
    monthText: "month",
    offText: "OFF",
    inquireTitle: "Inquire About This Property",
    inquireSubtitle: "Send your details to the agent.",
    priceSummary: "Price Summary",
    baseRent: "Base Rent",
    promoDiscount: "Promotional Discount",
    finalPrice: "Final Price",
    fullName: "Full Name",
    emailAddress: "Email Address",
    moveInDate: "Move-in Date",
    msgToAgent: "Message to Agent",
    scheduleVisit: "Schedule a visit",
    requestCallback: "Request a callback",
    sendInquiry: "Send Inquiry",
    verifiedProperty: "Verified Property",
    docsChecked: "Documents checked by To-Let Pro.",
    secureInquiry: "Secure Inquiry",
    dataPrivate: "Your details are kept private.",
    fastResponse: "Fast Response",
    agentNotified: "Agents are notified immediately.",
    typicallyReplies: "Typically replies within 1 hour",

    // Success Page
    successMainTitle: "Inquiry Sent Successfully!",
    successSubText: "Your request has been sent to the owner.",
    apartmentTag: "APARTMENT",
    yourDetailsTitle: "YOUR DETAILS",
    nameLabel: "NAME",
    phoneLabel: "PHONE",
    emailLabel: "EMAIL",
    backToHomeBtn: "Back to Home",
    viewMoreBtn: "View More Properties",

    // Auth Page
    welcomeBack: "Welcome Back!",
    createAccount: "Create Account",
    tenantRole: "Tenant",
    landlordRole: "Landlord",
    passPlaceholder: "Enter your password",
    namePlaceholder: "Full Name",
    forgotPass: "Forgot Password?",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    signUpNow: "Sign Up Now",
    loginNow: "Login Now",

    // Host Dashboard
    hostPortal: "Host Portal",
    managingLiving: "Managing Urban Living",
    newListing: "+ New Listing",
    dashboardMenu: "Dashboard",
    myProperties: "My Properties",
    inquiriesMenu: "Inquiries",
    bookings: "Bookings",
    earnings: "Earnings",
    settings: "Settings",
    supportMenu: "Support",
    portfolioOverview: "Portfolio Overview",
    managePremium: "Manage your premium properties in Dhaka.",
    totalProperties: "TOTAL PROPERTIES",
    totalInquiries: "TOTAL INQUIRIES",
    thisWeek: "this week",
    currentPortfolio: "Current Portfolio",
    filterBtn: "Filter",
    sortBtn: "Sort",
    activeBadge: "ACTIVE",
    rentedBadge: "RENTED",
    editBtn: "Edit",
    pauseBtn: "Pause",
    viewLeaseBtn: "View Lease",

    // Saved Properties
    savedTitle: "Saved Properties",
    savedSubtitle: "Your favorite picks, ready when you are.",
    removeBtn: "Remove",
    inquireNowBtn: "Inquire Now",
    exploreMore: "Explore More",

    // List Property
    listTitle: "List Your Property",
    step1Title: "Basic Info",
    step2Title: "Details",
    step3Title: "Amenities",
    step4Title: "Photos",
    step5Title: "Pricing",
    propTitle: "Property Title",
    propAddress: "Full Address",
    nextBtn: "Next Step",
    backBtn: "Back",
    submitListBtn: "Publish Listing",
    monthlyRent: "Monthly Rent (৳)",

    // Search UI labels
    typeLabel: "Type",
    budgetLabel: "Budget",
    popular: "Popular",
    popularAreas: "Popular Areas",
    useCurrentLocation: "Use current location",
    allAreas: "All Areas",
    suggestions: "Suggestions",
    matchingSuggestions: "Matching Suggestions",
    browseAllAreas: "Browse All Areas",
    customRange: "Custom Range (BDT)",
    applyRange: "Apply Range",
    searchProperties: "Search Properties",
    searchFor: "Search for",

    // Trust badges
    verifiedHosts: "Verified Hosts",
    instantBooking: "Instant Booking",
    support247: "24/7 Support",

    // App promo banner
    limitedTimeOffer: "Limited Time Offer",
    promoBannerTitle: "Find your dream home 10× faster",
    promoBannerDesc: "Download the TO-LET PRO app and get instant alerts when a property matching your criteria goes live. Zero brokerage fees.",
    availableOn: "Available on",
    priceLabel: "Price",
    getApp: "Get the App",

    // Popular divisions slider
    exploreDivisions: "Explore Divisions",
    exploreDivisionsDesc: "Discover properties across all major cities",

    // Host promo banner
    premiumHostOffer: "Premium Host Offer",
    hostBannerTitle: "List your property today and get 50% off premium placement",
    hostBannerDesc: "Join the fastest growing real estate network in Bangladesh. Verified leads, instant booking, and dedicated host support.",
    claimOfferNow: "Claim Offer Now",

    // Dhaka's Finest
    dhakasFinestDesc: "Premium living spaces in top-tier neighborhoods",
    exploreAll: "Explore All",
    avgRent: "Avg. Rent",

    // Social proof / Powered by Trust
    trustedByBD: "Trusted by Bangladesh",
    poweredByTrust: "Powered by Trust",
    poweredByTrustDesc: "The largest, most secure, and technologically advanced property rental network in Bangladesh — loved by real people.",
    statActiveUsers: "Active Users",
    statVerifiedHomes: "Verified Homes",
    statAppRating: "App Rating",
    nationwideNetworkSub: "Nationwide network",
    growingDaily: "And growing daily",
    zeroFakeListings: "Zero fake listings",
    reviewsCount: "12,000+ reviews",
    overallRating: "Overall Rating",
    basedOnReviews: "Based on 12,400+ verified reviews",
    appStore: "App Store",
    googlePlay: "Google Play",
    smartAITitle: "Smart AI-Powered Search",
    smartAIDesc: "Our NLP engine learns your preferences and surfaces the exact homes you'd love — before you even finish typing.",
    happyUsers: "+1M happy users",

    // Testimonials
    testimonial1Name: "Farhan Ahmed",
    testimonial1Role: "Software Engineer · Dhaka",
    testimonial1Badge: "Found home in 2 days",
    testimonial1Text: "I moved to Dhaka for work and found a perfect furnished apartment in Banani within two days. The verified host feature gave me so much confidence — no broker, no hassle.",
    testimonial1Area: "Banani, Dhaka",
    testimonial1Type: "Family Apartment",
    testimonial2Name: "Nusrat Jahan",
    testimonial2Role: "University Student · Chittagong",
    testimonial2Badge: "Saved ৳15,000 in fees",
    testimonial2Text: "As a female student, safety was my top priority. TO-LET PRO showed only verified female-friendly sublets. The live chat with hosts before visiting was a game-changer.",
    testimonial2Area: "GEC Circle, Chattogram",
    testimonial2Type: "Sublet Room",
    testimonial3Name: "Rakibul Islam",
    testimonial3Role: "Entrepreneur · Sylhet",
    testimonial3Badge: "Office found in 1 week",
    testimonial3Text: "Listed my commercial space and got three serious inquiries the same day. The platform is incredibly professional. I've recommended it to every business owner I know.",
    testimonial3Area: "Zindabazar, Sylhet",
    testimonial3Type: "Commercial Space",

    // Footer
    exploreFooter: "Explore",
    legalFooter: "Legal",
    contactUs: "Contact Us",
    allProperties: "All Properties",
    popularDistrictsFooter: "Popular Districts",
    commercialSpaces: "Commercial Spaces",
    hostDashboard: "Host Dashboard",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    trustSafety: "Trust & Safety",
    refundPolicy: "Refund Policy",
    builtInBD: "Built with love in Bangladesh",

    // Dictionaries
    cities: { chittagong: "Chittagong", dhaka: "Dhaka", sylhet: "Sylhet", rajshahi: "Rajshahi", khulna: "Khulna", barishal: "Barishal", rangpur: "Rangpur", mymensingh: "Mymensingh" },
    cityTags: { chittagong: "Port City", dhaka: "Premier Capital", sylhet: "Nature Hub", rajshahi: "Education City", khulna: "Industrial Hub", barishal: "River City", rangpur: "Heritage", mymensingh: "Cultural Hub" },
    districtNames: { dhanmondi: "Dhanmondi", gulshan: "Gulshan", banani: "Banani", bashundhara: "Bashundhara", mirpur: "Mirpur", mohammadpur: "Mohammadpur" },
    divisions: { Dhaka: ["Dhaka", "Gazipur", "Narayanganj"], Chittagong: ["Chattogram", "Cox's Bazar", "Comilla"], Sylhet: ["Sylhet", "Moulvibazar"], Rajshahi: ["Rajshahi", "Bogura"], Khulna: ["Khulna", "Jashore"], Barishal: ["Barishal", "Bhola"], Rangpur: ["Rangpur", "Dinajpur"], Mymensingh: ["Mymensingh", "Jamalpur"] },

    // ─── Mobile Home (mobile/MobileHome.jsx) ──────────────────────────────
    mobHeroLine1: "Find Your Next",
    mobHeroLine2: "Perfect Home",
    mobHeroSubtitle: "Verified hosts. Zero brokerage. Trusted by 1M+ Bangladeshis.",
    mobSearchAnywhere: "Search Anywhere",
    mobLocationLabel: "Location",
    mobLocationPlaceholderRent: "Where do you want to live?",
    mobLocationPlaceholderBuy: "Search city, neighborhood, or property to buy…",
    mobLocationPlaceholderCommercial: "Search commercial zone, building, or landmark…",
    mobMatchingSuggestions: "Matching suggestions",
    mobNoMatches: "No matches. Try a different area.",
    mobTypeLabel: "Type",
    mobBudgetLabel: "Budget",
    mobSearchProperties: "Search Properties",
    mobVerifiedHosts: "Verified hosts",
    mobSecurePrivate: "Secure & private",
    mobInstantBooking: "Instant booking",
    mobExploreDivisions: "Explore Divisions",
    mobExploreDivisionsSub: "Tap any division to see its districts",
    mobDistricts: "districts",
    mobPickDistrict: "Pick a district",
    mobViewHomes: "View homes",
    mobDivisionText: "Division",
    mobPopularAreas: "Popular Areas",
    mobPopularAreasSub: "Tap any area to see live listings",
    mobRecentlyPosted: "Recently posted",
    mobHomesIn: "Homes in",
    mobHomesPostedLast2: "homes posted in the last 2 days",
    mobHomePostedLast2: "home posted in the last 2 days",
    mobNoHomesYet: "No homes match this filter yet",
    mobNoHomesDesc: "We'll alert you the moment something lands. Try clearing the filter to see more.",
    mobClearFilters: "Clear filters",
    mobHavePropertyKicker: "Have a property?",
    mobHavePropertyTitle: "Let it out easily — list in 3 min",
    mobHavePropertySub: "Reach 50,000+ verified tenants today.",
    mobEndToEndSecured: "End-to-end secured by TO-LET PRO",
    mobNewToday: "New today",
    mobDayAgo: "day ago",
    mobDaysAgo: "days ago",
    mobMonth: "mo",
    mobBed: "bed",
    mobBath: "bath",
    mobReviews: "reviews",
    mobVerified: "VERIFIED",
    mobApartment: "APARTMENT",
    mobFamilyFlat: "FAMILY FLAT",
    mobBachelor: "BACHELOR",
    mobStudio: "STUDIO",
    mobSublet: "SUBLET",
    mobStudent: "STUDENT",
    mobPremium: "PREMIUM",
    mobHot: "HOT",
  },

  'বাংলা': {
    // Navbar & Hero
    brand: "টু-লেট প্রো", 
    business: "ব্যবসা", 
    listProperty: "প্রপার্টি দিন", 
    login: "লগইন / সাইনআপ", 
    allCities: "সব শহর",
    findYourNext: "খুঁজে নিন আপনার", 
    sweetHome: "স্বপ্নের ঠিকানা",

    // Hero Section
    heroTagline: "বাংলাদেশের ১নং প্রপার্টি প্ল্যাটফর্ম",
    heroTitle1: "খুঁজে নিন আপনার",
    heroTitle2: "স্বপ্নের ঠিকানা",
    heroSubtext: "১০০% ভেরিফাইড হোস্টদের সাথে ঢাকা ও সারা বাংলাদেশের সেরা সব অ্যাপার্টমেন্ট, ডুপ্লেক্স এবং কমার্শিয়াল স্পেস খুঁজে নিন।",
    tabRent: "ভাড়া",
    tabBuy: "ক্রয়",
    tabCommercial: "বাণিজ্যিক",
    searchLocation: "লোকেশন",
    locationPlaceholder: "কোথায় থাকতে চান?",
    searchType: "প্রপার্টির ধরন",
    searchBudget: "বাজেট",
    searchBtn: "খুঁজুন",
    typeAny: "যেকোনো প্রপার্টি",
    typeApt: "অ্যাপার্টমেন্ট",
    typeDuplex: "ডুপ্লেক্স",
    typeStudio: "স্টুডিও",
    budgetAny: "বাজেট নির্বাচন করুন",
    budgetLow: "২০ হাজার এর নিচে",
    budgetMid: "২০ হাজার - ৫০ হাজার",
    budgetHigh: "৫০ হাজার - ১ লাখ",
    budgetPremium: "১ লাখ এর ওপরে",
    
    // Browse By Location Section
    premiumLocations: "প্রিমিয়াম লোকেশন",
    browseBy: "খুঁজুন আপনার",
    locationText: "পছন্দের শহরে",
    viewFeatured: "প্রধান শহরগুলো দেখুন",
    viewAllCities: "সব শহর দেখুন",
    listings: "টি প্রপার্টি",

    // Popular Locations Section
    primeLocations: "প্রাইম লোকেশন",
    dhakasFinest: "ঢাকার সেরা",
    districts: "এলাকাসমূহ",
    districtsDesc: "আধুনিক পেশাজীবী এবং পারিবারিক জীবনের জন্য বাছাইকৃত প্রিমিয়াম আবাসিক এলাকা।",
    viewAllNeighborhoods: "সব এলাকা দেখুন",
    viewLess: "কম দেখান",
    premiumListings: "টি প্রিমিয়াম লিস্টিং",
    
    // Uttara Banner
    uttaraSectors: "উত্তরা সেক্টরস",
    uttaraDesc: "পরিকল্পিত লেআউট, বিমানবন্দর এবং প্রস্তাবিত মেট্রো রেলের সাথে চমৎকার যোগাযোগ ব্যবস্থাসম্পন্ন অনন্য আবাসিক এলাকা।",
    exploreSectorListings: "সেক্টর লিস্টিং এক্সপ্লোর করুন",

    // Stats Section
    dhakaCentral: "মধ্য ঢাকা",
    sylhetHills: "সিলেটের পাহাড়",
    chittagongPort: "চট্টগ্রাম বন্দর",
    nationwideNetwork: "দেশব্যাপী নেটওয়ার্ক",
    statsTitle1: "টু-লেট আছে আপনার",
    statsTitleAround: "আশেপাশেই।",
    statsTitleAlways: "সবসময়।",
    statsDesc: "দেশব্যাপী বিস্তৃত আমাদের নেটওয়ার্ক। শহরের বিলাসবহুল ফ্ল্যাট হোক বা শহরতলির শান্ত ভিলা, সব চাবি আছে আমাদের কাছে।",
    districtsCovered: "জেলা কভার করা হয়েছে",
    activeListings: "অ্যাক্টিভ লিস্টিং",
    divisionText: "বিভাগ",

    // CTA Section
    joinFuture: "ভাড়ার ভবিষ্যৎ এর সাথে যুক্ত হোন",
    readyToList: "আপনার প্রপার্টি ভাড়া দিতে",
    spaceText: "প্রস্তুত?",
    ctaDesc: "৫,০০০+ বিশ্বস্ত ল্যান্ডলর্ডদের সাথে যুক্ত হোন যারা ইতিমধ্যেই বাংলাদেশের সবচেয়ে প্রিমিয়াম রেন্টাল প্ল্যাটফর্মের মাধ্যমে সঠিক ভাড়াটিয়া খুঁজে পেয়েছেন।",
    getStartedFree: "ফ্রি-তে শুরু করুন",
    learnMoreBtn: "আরও জানুন",

    // Footer Section
    footerDesc: "বাছাইকৃত প্রিমিয়াম লিস্টিং এবং আধুনিক প্রযুক্তির মাধ্যমে বাংলাদেশের রেন্টাল অভিজ্ঞতাকে অনন্য উচ্চতায় নিয়ে যাওয়া।",
    discoveryTitle: "ডিসকভারি",
    navNewListings: "নতুন লিস্টিং",
    navPopularAreas: "জনপ্রিয় এলাকা",
    navAffordableStudios: "সাশ্রয়ী স্টুডিও",
    navLuxuryFlats: "লাক্সারি ফ্ল্যাট",
    landlordsTitle: "ল্যান্ডলর্ডদের জন্য",
    navHowItWorks: "কীভাবে কাজ করে",
    navListProperty: "প্রপার্টি দিন",
    navTrustSafety: "বিশ্বাস ও নিরাপত্তা",
    navHostGuidelines: "হোস্ট গাইডলাইন",
    stayInspired: "অনুপ্রাণিত থাকুন",
    newsletterDesc: "বাছাইকৃত বাড়ির সুপারিশ পেতে আমাদের নিউজলেটারে যুক্ত হোন।",
    emailPlaceholder: "আপনার ইমেইল দিন",
    footerCopyright: "© ২০২৬ টু-লেট প্রো। সর্বস্বত্ব সংরক্ষিত।",
    privacyPolicyUpper: "গোপনীয়তা নীতি",
    termsServiceUpper: "শর্তাবলী",
    cookiesUpper: "কুকিজ",

    // Filters & Property Listing
    activeFilters: "অ্যাক্টিভ ফিল্টার",
    clearAll: "সব মুছুন",
    sortNewest: "নতুন লিস্টিং",
    sortPriceLowHigh: "দাম: কম → বেশি",
    sortPriceHighLow: "দাম: বেশি → কম",
    sortPopular: "সবচেয়ে জনপ্রিয়",
    filtersBtn: "ফিল্টার",
    advancedFilter: "অ্যাডভান্সড",
    filterWord: "ফিল্টার",
    bangladesh: "বাংলাদেশ",
    filterLocation: "এলাকা",
    searchWithin: "খুঁজুন",
    filterPrice: "ভাড়ার বাজেট",
    minPrice: "সর্বনিম্ন ভাড়া",
    maxPrice: "সর্বোচ্চ ভাড়া",
    filterPropType: "বাসার ধরন",
    propApartment: "ফ্ল্যাট / অ্যাপার্টমেন্ট",
    propIndependent: "আলাদা বাসা",
    propDuplex: "ডুপ্লেক্স বাসা",
    propStudio: "স্টুডিও ফ্ল্যাট",
    propPenthouse: "পেন্টহাউস",
    filterRooms: "রুম ও বাথরুম",
    bedrooms: "শোবার রুম",
    bathroomType: "বাথরুম",
    any: "যেকোনো",
    attachedBath: "নিজস্ব বাথরুম",
    sharedBath: "শেয়ার বাথরুম",
    filterSize: "জায়গা (স্কয়ার ফিট)",
    maxSize: "সর্বোচ্চ জায়গা:",
    filterUtilities: "ভাড়ার সাথে যে বিল‌গুলো",
    waterBill: "পানি",
    electricityBill: "বিদ্যুৎ বিল",
    gasSupply: "গ্যাস সংযোগ",
    internetWifi: "ইন্টারনেট / ওয়াইফাই",
    serviceCharge: "সার্ভিস চার্জ",
    filterTenant: "কে উঠবে ও বাসা কেমন",
    tenantType: "কে উঠবে",
    family: "পরিবার",
    bachelor: "ব্যাচেলর",
    students: "ছাত্র-ছাত্রী",
    petsAllowed: "পোষা প্রাণী রাখা যাবে",
    // Rental category labels (shared by chip group on the listing page)
    filterWhoMovesIn: "কে উঠবে?",
    catFamilyFlat: "পরিবার (ফ্ল্যাট)",
    catBachelorMale: "ব্যাচেলর (ছেলে)",
    catBachelorFemale: "ব্যাচেলর (মেয়ে)",
    catSubletRoom: "সাবলেট / রুম",
    catStudent: "ছাত্র-ছাত্রী",
    // Quick budget pills shown above the price slider
    quickBudgetLabel: "দ্রুত বাজেট",
    budgetUpto15k: "১৫k এর নিচে",
    budgetUpto25k: "১৫k–২৫k",
    budgetUpto40k: "২৫k–৪০k",
    budgetUpto60k: "৪০k–৬০k",
    budgetAbove60k: "৬০k এর উপরে",
    furnishing: "আসবাবপত্র",
    furnished: "আসবাবপত্রসহ",
    semiFurnished: "কিছু আসবাবসহ",
    unfurnished: "আসবাবপত্র ছাড়া",
    filterAmenities: "অন্যান্য সুবিধা ও তলা",
    amenities: "সুযোগ-সুবিধা",
    parking: "গাড়ি পার্কিং",
    elevator: "লিফট",
    generator: "জেনারেটর",
    securityCctv: "সিসিটিভি / নিরাপত্তা",
    ac: "এসি",
    floorLevel: "কোন তলা",
    anyFloor: "যেকোনো তলা",
    groundFloor: "নিচতলা",
    floor1to3: "১ম–৩য় তলা",
    floor4to7: "৪র্থ–৭ম তলা",
    floor8Plus: "৮ম তলা বা উপরে",
    filterFinancials: "অ্যাডভান্স ও কবে উঠা যাবে",
    depositAdvance: "অ্যাডভান্স",
    noAdvance: "অ্যাডভান্স লাগবে না",
    monthAdvance1: "১ মাসের অ্যাডভান্স",
    monthAdvance2: "২ মাসের অ্যাডভান্স",
    negotiableDeposit: "কথা বলে ঠিক হবে",
    availability: "কবে উঠা যাবে",
    availableNow: "এখনই উঠা যাবে",
    availableThisMonth: "এই মাসে",
    availableNextMonth: "পরের মাসে",
    filterRating: "বাসার রেটিং",
    star4Above: "৪.০ ও তার উপরে",
    star3Above: "৩.০ ও তার উপরে",
    anyRating: "যেকোনো রেটিং",
    applyFiltersBtn: "ফিল্টার দেখান",
    searchAreaPlaceholder: "এলাকার নাম লিখুন...",
    nearMe: "আমার কাছাকাছি",
    locating: "খুঁজছে...",
    showing: "দেখাচ্ছে",
    backToTop: "ওপরে যান",
    home: "হোম",
    sortBy: "সাজান:",
    reviews: "রিভিউ",
    inquiriesToday: "আজকের ইনকোয়ারি",
    off: "ছাড়",
    perMonthExcluding: "প্রতি মাস • ইউটিলিটি বাদে",
    detailsBtn: "বিস্তারিত",
    clearFilters: "ফিল্টার মুছুন",

    // Property Card & Details
    properties: "প্রপার্টিসমূহ",
    verified: "ভেরিফাইড",
    monthlyRentText: "মাসিক ভাড়া",
    inquireBtn: "যোগাযোগ করুন",
    beds: "বেড",
    baths: "বাথ",
    sqft: "বর্গফুট",
    noPropsFound: "কোনো প্রপার্টি পাওয়া যায়নি",
    noPropsDesc: "এর জন্য কোনো লিস্টিং পাওয়া যায়নি।",
    adjustFilters: "আপনার ফিল্টার পরিবর্তন করে দেখুন।",
    backToResults: "সার্চে ফিরে যান",
    aboutProperty: "এই প্রপার্টি সম্পর্কে",
    propertyDesc: "শহরের প্রাণকেন্দ্রে অতুলনীয় বিলাসবহুল অভিজ্ঞতার স্বাদ নিন।",
    amenitiesTitle: "সুযোগ-সুবিধা",
    propDetailsTitle: "প্রপার্টির বিবরণ",
    listedBy: "লিস্টিং করেছেন",
    viewProfile: "প্রোফাইল দেখুন",
    callNow: "কল করুন",
    messageBtn: "মেসেজ দিন",
    requestDetails: "রিকোয়েস্ট ডিটেইলস",
    yourName: "আপনার নাম",
    phoneNum: "ফোন নম্বর",
    messageLabel: "মেসেজ",
    defaultMsg: "আমি এই প্রপার্টিটি ভাড়া নিতে আগ্রহী।",
    submitInquiry: "ইনকোয়ারি জমা দিন",
    share: "শেয়ার",
    save: "সেভ করুন",
    availableImmed: "এখনই উঠা যাবে",
    monthText: "মাস",
    offText: "ছাড়",
    inquireTitle: "এই প্রপার্টি সম্পর্কে ইনকোয়ারি করুন",
    inquireSubtitle: "আপনার তথ্য এজেন্টকে পাঠান।",
    priceSummary: "ভাড়ার বিবরণ",
    baseRent: "মূল ভাড়া",
    promoDiscount: "প্রোমোশনাল ছাড়",
    finalPrice: "মোট ভাড়া",
    fullName: "সম্পূর্ণ নাম",
    emailAddress: "ইমেইল অ্যাড্রেস",
    moveInDate: "কবে উঠতে চান",
    msgToAgent: "এজেন্টকে মেসেজ দিন",
    scheduleVisit: "পরিদর্শনে যেতে চাই",
    requestCallback: "কলব্যাক রিকোয়েস্ট",
    sendInquiry: "ইনকোয়ারি পাঠান",
    verifiedProperty: "ভেরিফাইড প্রপার্টি",
    docsChecked: "টু-লেট প্রো দ্বারা যাচাইকৃত।",
    secureInquiry: "সুরক্ষিত ইনকোয়ারি",
    dataPrivate: "আপনার তথ্য নিরাপদ থাকবে।",
    fastResponse: "দ্রুত রেসপন্স",
    agentNotified: "এজেন্টকে সাথে সাথে জানানো হয়।",
    typicallyReplies: "সাধারণত ১ ঘণ্টার মধ্যে রিপ্লাই দেয়",

    // Success Page
    successMainTitle: "ইনকোয়ারি সফলভাবে পাঠানো হয়েছে!",
    successSubText: "আপনার রিকোয়েস্ট প্রপার্টির মালিকের কাছে পাঠানো হয়েছে।",
    apartmentTag: "অ্যাপার্টমেন্ট",
    yourDetailsTitle: "আপনার বিস্তারিত তথ্য",
    nameLabel: "নাম",
    phoneLabel: "ফোন",
    emailLabel: "ইমেইল",
    backToHomeBtn: "হোমে ফিরে যান",
    viewMoreBtn: "আরও প্রপার্টি দেখুন",

    // Auth Page
    welcomeBack: "স্বাগতম!",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    tenantRole: "ভাড়াটিয়া",
    landlordRole: "মালিক",
    passPlaceholder: "আপনার পাসওয়ার্ড দিন",
    namePlaceholder: "সম্পূর্ণ নাম",
    forgotPass: "পাসওয়ার্ড ভুলে গেছেন?",
    noAccount: "অ্যাকাউন্ট নেই?",
    hasAccount: "আগে থেকেই অ্যাকাউন্ট আছে?",
    signUpNow: "এখনই সাইন আপ করুন",
    loginNow: "এখনই লগইন করুন",

    // Host Dashboard
    hostPortal: "হোস্ট পোর্টাল",
    managingLiving: "আরবান লিভিং ম্যানেজমেন্ট",
    newListing: "+ নতুন লিস্টিং",
    dashboardMenu: "ড্যাশবোর্ড",
    myProperties: "আমার প্রপার্টি",
    inquiriesMenu: "ইনকোয়ারি",
    bookings: "বুকিং",
    earnings: "উপার্জন",
    settings: "সেটিংস",
    supportMenu: "সাপোর্ট",
    portfolioOverview: "পোর্টফোলিও ওভারভিউ",
    managePremium: "ঢাকায় আপনার প্রিমিয়াম প্রপার্টি পরিচালনা করুন।",
    totalProperties: "মোট প্রপার্টি",
    totalInquiries: "মোট ইনকোয়ারি",
    thisWeek: "এই সপ্তাহে",
    currentPortfolio: "বর্তমান পোর্টফোলিও",
    filterBtn: "ফিল্টার",
    sortBtn: "সর্ট",
    activeBadge: "সক্রিয়",
    rentedBadge: "ভাড়ায় চালিত",
    editBtn: "এডিট",
    pauseBtn: "পজ",
    viewLeaseBtn: "লিজ দেখুন",

    // Saved Properties
    savedTitle: "সেভ করা প্রপার্টি",
    savedSubtitle: "আপনার পছন্দের তালিকা, এক নজরে।",
    removeBtn: "রিমুভ করুন",
    inquireNowBtn: "ইনকোয়ারি করুন",
    exploreMore: "আরও খুঁজুন",

    // List Property
    listTitle: "আপনার প্রপার্টি লিস্ট করুন",
    step1Title: "সাধারণ তথ্য",
    step2Title: "বিস্তারিত",
    step3Title: "সুযোগ-সুবিধা",
    step4Title: "ছবি",
    step5Title: "ভাড়া",
    propTitle: "প্রপার্টির নাম",
    propAddress: "সম্পূর্ণ ঠিকানা",
    nextBtn: "পরবর্তী ধাপ",
    backBtn: "পেছনে",
    submitListBtn: "পাবলিশ করুন",
    monthlyRent: "মাসিক ভাড়া (৳)",
    Inquire: "যোগাযোগ করুন",
    Inquiries: "যোগাযোগ সমূহ",
    Messages: "বার্তা",
    Support: "সহায়তা",
    Bookings: "ভাড়ার তালিকা",

    // Search UI labels
    typeLabel: "ধরন",
    budgetLabel: "বাজেট",
    popular: "জনপ্রিয়",
    popularAreas: "জনপ্রিয় এলাকা",
    useCurrentLocation: "বর্তমান লোকেশন ব্যবহার করুন",
    allAreas: "সব এলাকা",
    suggestions: "পরামর্শ",
    matchingSuggestions: "মিলে যাওয়া ফলাফল",
    browseAllAreas: "সব এলাকা দেখুন",
    customRange: "কাস্টম রেঞ্জ (৳)",
    applyRange: "রেঞ্জ প্রয়োগ করুন",
    searchProperties: "প্রপার্টি খুঁজুন",
    searchFor: "খুঁজুন",

    // Trust badges
    verifiedHosts: "ভেরিফাইড হোস্ট",
    instantBooking: "তাৎক্ষণিক বুকিং",
    support247: "২৪/৭ সাপোর্ট",

    // App promo banner
    limitedTimeOffer: "সীমিত সময়ের অফার",
    promoBannerTitle: "১০ গুণ দ্রুত খুঁজুন স্বপ্নের বাড়ি",
    promoBannerDesc: "টু-লেট প্রো অ্যাপ ডাউনলোড করুন এবং আপনার পছন্দের প্রপার্টি উপলব্ধ হলেই তাৎক্ষণিক নোটিফিকেশন পান। শূন্য দালাল ফি।",
    availableOn: "পাওয়া যাচ্ছে",
    priceLabel: "মূল্য",
    getApp: "অ্যাপ ডাউনলোড করুন",

    // Popular divisions slider
    exploreDivisions: "বিভাগ অন্বেষণ করুন",
    exploreDivisionsDesc: "প্রধান শহরগুলোতে প্রপার্টি আবিষ্কার করুন",

    // Host promo banner
    premiumHostOffer: "প্রিমিয়াম হোস্ট অফার",
    hostBannerTitle: "আজই আপনার প্রপার্টি লিস্ট করুন এবং ৫০% ছাড় পান",
    hostBannerDesc: "বাংলাদেশের সবচেয়ে দ্রুত বর্ধনশীল রিয়েল এস্টেট নেটওয়ার্কে যোগ দিন। ভেরিফাইড লিড, তাৎক্ষণিক বুকিং, এবং ডেডিকেটেড হোস্ট সাপোর্ট।",
    claimOfferNow: "অফার নিন এখনই",

    // Dhaka's Finest
    dhakasFinestDesc: "শীর্ষ-মানের আবাসিক এলাকায় প্রিমিয়াম বাসস্থান",
    exploreAll: "সব দেখুন",
    avgRent: "গড় ভাড়া",

    // Social proof / Powered by Trust
    trustedByBD: "বাংলাদেশের বিশ্বাস",
    poweredByTrust: "বিশ্বাসের শক্তিতে",
    poweredByTrustDesc: "বাংলাদেশের সবচেয়ে বড়, সবচেয়ে নিরাপদ এবং সবচেয়ে প্রযুক্তি-উন্নত প্রপার্টি রেন্টাল নেটওয়ার্ক — সত্যিকারের মানুষের পছন্দের।",
    statActiveUsers: "সক্রিয় ব্যবহারকারী",
    statVerifiedHomes: "ভেরিফাইড বাড়ি",
    statAppRating: "অ্যাপ রেটিং",
    nationwideNetworkSub: "দেশব্যাপী নেটওয়ার্ক",
    growingDaily: "প্রতিদিন বাড়ছে",
    zeroFakeListings: "কোনো ভুয়া লিস্টিং নেই",
    reviewsCount: "১২,০০০+ রিভিউ",
    overallRating: "সামগ্রিক রেটিং",
    basedOnReviews: "১২,৪০০+ যাচাইকৃত রিভিউর ভিত্তিতে",
    appStore: "অ্যাপ স্টোর",
    googlePlay: "গুগল প্লে",
    smartAITitle: "স্মার্ট AI-চালিত সার্চ",
    smartAIDesc: "আমাদের NLP ইঞ্জিন আপনার পছন্দ শিখে নেয় এবং আপনার টাইপ শেষ হওয়ার আগেই একদম সঠিক বাড়িগুলো দেখায়।",
    happyUsers: "+১০ লাখ সন্তুষ্ট ব্যবহারকারী",

    // Testimonials
    testimonial1Name: "ফারহান আহমেদ",
    testimonial1Role: "সফটওয়্যার ইঞ্জিনিয়ার · ঢাকা",
    testimonial1Badge: "২ দিনেই বাড়ি পেয়েছি",
    testimonial1Text: "কাজের জন্য ঢাকায় এসে মাত্র দুই দিনে বনানীতে একটি চমৎকার ফার্নিশড অ্যাপার্টমেন্ট পেয়েছি। ভেরিফাইড হোস্ট ফিচারটি আমাকে অনেক আত্মবিশ্বাস দিয়েছে — কোনো দালাল নেই, কোনো ঝামেলা নেই।",
    testimonial1Area: "বনানী, ঢাকা",
    testimonial1Type: "ফ্যামিলি অ্যাপার্টমেন্ট",
    testimonial2Name: "নুসরাত জাহান",
    testimonial2Role: "বিশ্ববিদ্যালয় শিক্ষার্থী · চট্টগ্রাম",
    testimonial2Badge: "৳১৫,০০০ ফি বাঁচিয়েছি",
    testimonial2Text: "মেয়ে শিক্ষার্থী হিসেবে নিরাপত্তা আমার কাছে সবচেয়ে গুরুত্বপূর্ণ ছিল। টু-লেট প্রো শুধু মেয়েদের জন্য ভেরিফাইড সাবলেট দেখিয়েছে। পরিদর্শনের আগে হোস্টের সাথে লাইভ চ্যাটের সুবিধাটি দারুণ ছিল।",
    testimonial2Area: "জিইসি সার্কেল, চট্টগ্রাম",
    testimonial2Type: "সাবলেট রুম",
    testimonial3Name: "রাকিবুল ইসলাম",
    testimonial3Role: "উদ্যোক্তা · সিলেট",
    testimonial3Badge: "১ সপ্তাহে অফিস পেয়েছি",
    testimonial3Text: "আমার কমার্শিয়াল স্পেস লিস্ট করার একই দিনে তিনটি গুরুতর ইনকোয়ারি পেয়েছি। প্ল্যাটফর্মটি অবিশ্বাস্য রকম পেশাদার। আমি আমার পরিচিত সব ব্যবসায়ীকে এটি সুপারিশ করেছি।",
    testimonial3Area: "জিন্দাবাজার, সিলেট",
    testimonial3Type: "বাণিজ্যিক স্থান",

    // Footer
    exploreFooter: "অন্বেষণ",
    legalFooter: "আইনি",
    contactUs: "যোগাযোগ করুন",
    allProperties: "সব প্রপার্টি",
    popularDistrictsFooter: "জনপ্রিয় এলাকা",
    commercialSpaces: "বাণিজ্যিক স্থান",
    hostDashboard: "হোস্ট ড্যাশবোর্ড",
    termsOfService: "শর্তাবলী",
    privacyPolicy: "গোপনীয়তা নীতি",
    trustSafety: "বিশ্বাস ও নিরাপত্তা",
    refundPolicy: "ফেরত নীতি",
    builtInBD: "ভালোবাসায় বানানো বাংলাদেশে",

    // Dictionaries
    cities: { chittagong: "চট্টগ্রাম", dhaka: "ঢাকা", sylhet: "সিলেট", rajshahi: "রাজশাহী", khulna: "খুলনা", barishal: "বরিশাল", rangpur: "রংপুর", mymensingh: "ময়মনসিংহ" },
    cityTags: { chittagong: "বন্দর নগরী", dhaka: "প্রধান রাজধানী", sylhet: "প্রকৃতির কেন্দ্র", rajshahi: "শিক্ষা নগরী", khulna: "শিল্প কেন্দ্র", barishal: "নদীর শহর", rangpur: "ঐতিহ্যবাহী", mymensingh: "সাংস্কৃতিক কেন্দ্র" },
    districtNames: { dhanmondi: "ধানমন্ডি", gulshan: "গুলশান", banani: "বনানী", bashundhara: "বসুন্ধরা", mirpur: "মিরপুর", mohammadpur: "মোহাম্মদপুর" },
    divisions: { 'ঢাকা': ["ঢাকা", "গাজীপুর", "নারায়ণগঞ্জ"], 'চট্টগ্রাম': ["চট্টগ্রাম", "কক্সবাজার", "কুমিল্লা"], 'সিলেট': ["সিলেট", "মৌলভীবাজার"], 'রাজশাহী': ["রাজশাহী", "বগুড়া"], 'খুলনা': ["খুলনা", "যশোর"], 'বরিশাল': ["বরিশাল", "ভোলা"], 'রংপুর': ["রংপুর", "দিনাজপুর"], 'ময়মনসিংহ': ["ময়মনসিংহ", "জামালপুর"] },

    // ─── Mobile Home (mobile/MobileHome.jsx) ──────────────────────────────
    mobHeroLine1: "খুঁজে নিন আপনার",
    mobHeroLine2: "স্বপ্নের ঠিকানা",
    mobHeroSubtitle: "ভেরিফাইড হোস্ট। কোনো ব্রোকারেজ নয়। ১০ লাখের বেশি মানুষের আস্থা।",
    mobSearchAnywhere: "যেকোনো জায়গায় খুঁজুন",
    mobLocationLabel: "লোকেশন",
    mobLocationPlaceholderRent: "কোথায় থাকতে চান?",
    mobLocationPlaceholderBuy: "শহর, এলাকা বা প্রপার্টি খুঁজুন…",
    mobLocationPlaceholderCommercial: "কমার্শিয়াল জোন, বিল্ডিং বা ল্যান্ডমার্ক খুঁজুন…",
    mobMatchingSuggestions: "মিলে যাওয়া এলাকা",
    mobNoMatches: "মিল পাওয়া যায়নি। অন্য এলাকা চেষ্টা করুন।",
    mobTypeLabel: "ধরন",
    mobBudgetLabel: "বাজেট",
    mobSearchProperties: "প্রপার্টি খুঁজুন",
    mobVerifiedHosts: "ভেরিফাইড হোস্ট",
    mobSecurePrivate: "সুরক্ষিত ও ব্যক্তিগত",
    mobInstantBooking: "তাৎক্ষণিক বুকিং",
    mobExploreDivisions: "বিভাগ দেখুন",
    mobExploreDivisionsSub: "জেলা দেখতে যেকোনো বিভাগে ট্যাপ করুন",
    mobDistricts: "জেলা",
    mobPickDistrict: "একটি জেলা বাছাই করুন",
    mobViewHomes: "বাসা দেখুন",
    mobDivisionText: "বিভাগ",
    mobPopularAreas: "জনপ্রিয় এলাকা",
    mobPopularAreasSub: "লাইভ লিস্টিং দেখতে ট্যাপ করুন",
    mobRecentlyPosted: "সম্প্রতি যোগ হয়েছে",
    mobHomesIn: "এর বাসা",
    mobHomesPostedLast2: "টি বাসা গত ২ দিনে যোগ হয়েছে",
    mobHomePostedLast2: "টি বাসা গত ২ দিনে যোগ হয়েছে",
    mobNoHomesYet: "এই ফিল্টারের জন্য কোনো বাসা পাওয়া যায়নি",
    mobNoHomesDesc: "নতুন কিছু এলে আমরা সাথে সাথে জানাব। ফিল্টার সরিয়ে আরও দেখুন।",
    mobClearFilters: "ফিল্টার সরান",
    mobHavePropertyKicker: "প্রপার্টি আছে?",
    mobHavePropertyTitle: "৩ মিনিটেই ভাড়া দিন",
    mobHavePropertySub: "আজই ৫০,০০০+ ভেরিফাইড ভাড়াটিয়ার কাছে পৌঁছান।",
    mobEndToEndSecured: "টু-লেট প্রো দ্বারা সুরক্ষিত",
    mobNewToday: "আজ নতুন",
    mobDayAgo: "দিন আগে",
    mobDaysAgo: "দিন আগে",
    mobMonth: "মাস",
    mobBed: "বেড",
    mobBath: "বাথ",
    mobReviews: "রিভিউ",
    mobVerified: "ভেরিফাইড",
    mobApartment: "অ্যাপার্টমেন্ট",
    mobFamilyFlat: "ফ্যামিলি ফ্ল্যাট",
    mobBachelor: "ব্যাচেলর",
    mobStudio: "স্টুডিও",
    mobSublet: "সাবলেট",
    mobStudent: "ছাত্র/ছাত্রী",
    mobPremium: "প্রিমিয়াম",
    mobHot: "হট",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(readInitialLanguage);

  // Wrap setLanguage so every change is persisted. Components keep calling
  // `setLanguage(name)` exactly like before — no change needed at call sites.
  const setLanguage = (next) => {
    setLanguageState(next);
    if (typeof window !== 'undefined') {
      try { window.localStorage.setItem(LANG_STORAGE_KEY, next); } catch { /* ignore */ }
    }
  };

  // Defensive: if a translation key is missing in the chosen language we
  // fall back to the English value rather than rendering `undefined`.
  const base = translations[language] || translations[DEFAULT_LANGUAGE];
  const fallback = translations['English'];
  const t = new Proxy(base, {
    get(target, prop) {
      const v = target[prop];
      return v !== undefined ? v : fallback[prop];
    },
  });

  // Keep <html lang="…"> in sync so screen readers + Chrome translate UI
  // pick up the language change.
  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language === 'বাংলা' ? 'bn' : 'en';
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);