import React, { createContext, useState, useContext, useEffect } from 'react';

// Storage key used to persist the user's language preference across reloads.
const LANG_STORAGE_KEY = 'tolet_lang';

// Bengali is the primary default — most TO-LET PRO users are Bangladeshi.
// Anyone who explicitly toggles to English still has their choice honoured
// because we save it to localStorage below.
const DEFAULT_LANGUAGE = 'বাংলা';

const readInitialLanguage = () => {
  if (typeof window === 'undefined') return DEFAULT_LANGUAGE;
  try {
    const stored = window.localStorage.getItem(LANG_STORAGE_KEY);
    if (stored === 'English' || stored === 'বাংলা') return stored;
  } catch {
    /* localStorage blocked (e.g. SSR / private mode) → fall through */
  }
  return DEFAULT_LANGUAGE;
};

const translations = {
  'English': {
    // Navbar & Hero
    brand: "TO-LET PRO", 
    business: "Business", 
    listProperty: "List Property", 
    login: "Login / Signup", 
    allCities: "ALL CITIES",
    findYourNext: "Find your next", 
    sweetHome: "Sweet Home",

    // ─── Mobile menu drawer (Navbar.jsx) ───
    menuJoinTitle: "Join TO-LET PRO",
    menuJoinSubtitle: "Dashboards, saved searches, alerts & more",
    menuLogIn: "Log In",
    menuSignUp: "Sign Up",
    menuTenantDashboard: "Tenant Dashboard",
    menuHostDashboard: "Host Dashboard",
    menuSavedProperties: "Saved Properties",
    menuMyInquiries: "My Inquiries",
    menuMyAlerts: "My Alerts",
    menuAddProperty: "Add Property",
    menuListingAnalytics: "Listing Analytics",
    menuTenantMessages: "Tenant Messages",
    menuSearchProperties: "Search Properties",
    menuListProperty: "List a Property",
    menuSwitchToHost: "Switch to Host",
    menuSwitchToTenant: "Switch to Tenant",
    menuHostModeActive: "Host mode active",
    menuTenantModeActive: "Tenant mode active",
    menuRoleHost: "Host",
    menuRoleTenant: "Tenant",
    menuBecomeLandlord: "I want to be a landlord",
    menuBecomeLandlordSub: "Rent out your property",
    menuBecomeLandlordCta: "Start",
    menuHelpSupport: "Help & Support",
    menuSettings: "Settings",
    menuTermsPolicies: "Terms & Policies",
    menuLanguageLabel: "Language",
    menuLogOut: "Log out",
    menuSectionAccount: "My Account",
    menuSectionExplore: "Explore",
    menuSectionSupport: "Support",
    navPricing: "Pricing",
    navHelp: "Help",
    navLogIn: "Log in",
    navSignUp: "Sign up",
    navImLandlord: "I'm a landlord",

    // Hero Section
    heroTagline: "Bangladesh's #1 Property Platform",
    heroTitle1: "Find Your Next",
    heroTitle2: "Perfect Home",
    heroSubtext: "Discover premium apartments, duplexes, and commercial spaces across Bangladesh with 100% verified hosts.",
    tabRent: "Rent",
    tabBuy: "Buy",
    tabCommercial: "Commercial",
    tabResidential: "Residential",
    searchLocation: "Location",
    locationPlaceholder: "Where do you want to live?",
    locationPlaceholderBuy: "City, area, or property…",
    locationPlaceholderCommercial: "Zone, building, or landmark…",
    searchType: "Property Type",
    searchBudget: "Budget Range",
    searchBtn: "Search",
    typeAny: "Any Property",
    typeApt: "Apartment",
    typeDuplex: "Duplex",
    typeStudio: "Studio",
    budgetAny: "Choose Range",
    budgetLow: "Below 20k",
    budgetMid: "20k - 50k",
    budgetHigh: "50k - 100k",
    budgetPremium: "Above 100k",
    
    // Browse By Location Section
    premiumLocations: "Premium Locations",
    browseBy: "Browse by",
    locationText: "Location",
    viewFeatured: "View Featured",
    viewAllCities: "View All Cities",
    listings: "Listings",

    // Popular Locations Section 
    primeLocations: "Prime Locations",
    dhakasFinest: "Dhaka's Finest",
    districts: "Districts",
    districtsDesc: "Premium urban hubs, curated for the modern professional and family living.",
    viewAllNeighborhoods: "View all neighborhoods",
    viewLess: "View less",
    premiumListings: "Premium Listings",
    
    // Uttara Banner
    uttaraSectors: "Uttara Sectors",
    uttaraDesc: "Unique residential sectors with planned layouts, excellent connectivity to the airport and upcoming metro rail.",
    exploreSectorListings: "Explore Sector Listings",
    
   // Stats Section
   dhakaCentral: "Dhaka Central",
   sylhetHills: "Sylhet Hills",
   chittagongPort: "Chittagong Port",
   nationwideNetwork: "Nationwide Network",
   statsTitle1: "There's a TO-LET",
   statsTitleAround: "around.",
   statsTitleAlways: "Always.",
   statsDesc: "Nationwide availability. Unmatched scale. Whether it's a bustling urban flat or a serene suburban villa, we have the keys.",
   districtsCovered: "Districts Covered",
   activeListings: "Active Listings",
   divisionText: "Division",

    // CTA Section
    joinFuture: "Join the Future of Renting",
    readyToList: "Ready to list your",
    spaceText: "space?",
    ctaDesc: "Join over 5,000 trusted hosts who have already found their perfect tenants through Bangladesh's most premium rental platform.",
    getStartedFree: "Get Started for Free",
    learnMoreBtn: "Learn More",

    // Footer Section
    footerDesc: "Elevating the rental experience in Bangladesh through curated premium listings and seamless modern technology.",
    discoveryTitle: "Discovery",
    navNewListings: "New Listings",
    navPopularAreas: "Popular Areas",
    navAffordableStudios: "Affordable Studios",
    navLuxuryFlats: "Luxury Flats",
    landlordsTitle: "For Landlords",
    navHowItWorks: "How it Works",
    navListProperty: "List a Property",
    navTrustSafety: "Trust & Safety",
    navHostGuidelines: "Host Guidelines",
    stayInspired: "Stay Inspired",
    newsletterDesc: "Join our newsletter for curated home recommendations.",
    emailPlaceholder: "Your email",
    footerCopyright: "© 2026 TO-LET PRO. ALL RIGHTS RESERVED.",
    privacyPolicyUpper: "PRIVACY POLICY",
    termsServiceUpper: "TERMS OF SERVICE",
    cookiesUpper: "COOKIES",

    // Filters & Property Listing
    activeFilters: "Active Filters",
    clearAll: "CLEAR ALL",
    sortNewest: "Newest Listings",
    sortPriceLowHigh: "Price Low → High",
    sortPriceHighLow: "Price High → Low",
    sortPopular: "Most Popular",
    filtersBtn: "Filters",
    advancedFilter: "Advanced",
    filterWord: "Filter",
    searchAreaPlaceholder: "Search area...",
    nearMe: "Near Me",
    locating: "Locating",
    filterPrice: "Price Range",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    filterPropType: "Property Type",
    propApartment: "Apartment",
    propIndependent: "Independent House",
    propDuplex: "Duplex",
    propStudio: "Studio",
    propPenthouse: "Penthouse",
    filterRooms: "Bedrooms & Bathrooms",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    bathroomType: "Bathroom Type",
    any: "Any",
    attachedBath: "Attached",
    sharedBath: "Shared",
    filterSize: "Size (Area Sqft)",
    maxSize: "Max Size:",
    filterUtilities: "Utilities Included",
    waterBill: "Water Bill",
    electricityBill: "Electricity Bill",
    gasSupply: "Gas Supply",
    internetWifi: "Internet/WiFi",
    serviceCharge: "Service Charge",
    filterTenant: "Who's moving in",
    tenantType: "Who's moving in?",
    family: "Family",
    bachelor: "Bachelor",
    students: "Students",
    petsAllowed: "Pets allowed",
    // Rental category labels (shared by chip group on the listing page)
    filterWhoMovesIn: "Who's moving in?",
    catFamilyFlat: "Family Flat",
    catBachelorMale: "Bachelor (Male)",
    catBachelorFemale: "Bachelor (Female)",
    catSubletRoom: "Sublet / Room",
    catStudent: "Student",
    // Quick budget pills shown above the price slider
    quickBudgetLabel: "Quick budget",
    budgetUpto15k: "Under ৳15k",
    budgetUpto25k: "৳15k–৳25k",
    budgetUpto40k: "৳25k–৳40k",
    budgetUpto60k: "৳40k–৳60k",
    budgetAbove60k: "Above ৳60k",
    furnishing: "Furnishing",
    furnished: "Furnished",
    semiFurnished: "Semi-Furnished",
    unfurnished: "Unfurnished",
    filterAmenities: "Amenities & Floor",
    amenities: "Amenities",
    parking: "Parking",
    elevator: "Elevator",
    generator: "Generator",
    securityCctv: "Security/CCTV",
    ac: "AC",
    floorLevel: "Floor Level",
    anyFloor: "Any Floor",
    groundFloor: "Ground Floor",
    floor1to3: "1st to 3rd Floor",
    floor4to7: "4–7 Floor",
    floor8Plus: "8+ Floor",
    filterFinancials: "Deposit & Availability",
    depositAdvance: "Deposit / Advance",
    noAdvance: "No Advance",
    monthAdvance1: "1 Month Advance",
    monthAdvance2: "2 Months Advance",
    negotiableDeposit: "Negotiable Deposit",
    availability: "Availability",
    availableNow: "Available Now",
    availableThisMonth: "Available This Month",
    availableNextMonth: "Available Next Month",
    filterRating: "Property Rating",
    star4Above: "4★ & Above",
    star3Above: "3★ & Above",
    anyRating: "Any Rating",
    applyFiltersBtn: "Apply Filters",
    showing: "Showing",
    backToTop: "Back to Top",
    home: "Home",
    sortBy: "Sort by:",
    reviews: "Reviews",
    inquiriesToday: "Inquiries Today",
    off: "Off",
    perMonthExcluding: "Per Month • Excluding Utilities",
    detailsBtn: "Details",
    clearFilters: "Clear Filters",
    searchWithin: "Search within",

    // Property Card & Details
    properties: "Properties",
    verified: "VERIFIED",
    monthlyRentText: "Monthly Rent",
    inquireBtn: "INQUIRE",
    beds: "Beds",
    baths: "Baths",
    sqft: "sqft",
    noPropsFound: "No properties found",
    noPropsDesc: "We couldn't find any listings for",
    adjustFilters: "Try adjusting your filters.",
    bangladesh: "Bangladesh",
    backToResults: "Back to Search",
    aboutProperty: "About this property",
    propertyDesc: "Experience unparalleled luxury in the heart of the city.",
    amenitiesTitle: "Amenities",
    propDetailsTitle: "Property Details",
    listedBy: "LISTED BY",
    viewProfile: "View Profile",
    callNow: "Call Now",
    messageBtn: "Message",
    requestDetails: "Request Details",
    yourName: "Your Name",
    phoneNum: "Phone Number",
    messageLabel: "Message",
    defaultMsg: "I am interested in this property.",
    submitInquiry: "Submit Inquiry",
    share: "Share",
    save: "Save",
    availableImmed: "Available Immediately",
    monthText: "month",
    offText: "OFF",
    inquireTitle: "Inquire About This Property",
    inquireSubtitle: "Send your details to the agent.",
    priceSummary: "Price Summary",
    baseRent: "Base Rent",
    promoDiscount: "Promotional Discount",
    finalPrice: "Final Price",
    fullName: "Full Name",
    emailAddress: "Email Address",
    moveInDate: "Move-in Date",
    msgToAgent: "Message to Agent",
    scheduleVisit: "Schedule a visit",
    requestCallback: "Request a callback",
    sendInquiry: "Send Inquiry",
    verifiedProperty: "Verified Property",
    docsChecked: "Documents checked by To-Let Pro.",
    secureInquiry: "Secure Inquiry",
    dataPrivate: "Your details are kept private.",
    fastResponse: "Fast Response",
    agentNotified: "Agents are notified immediately.",
    typicallyReplies: "Typically replies within 1 hour",

    // Success Page
    successMainTitle: "Inquiry Sent Successfully!",
    successSubText: "Your request has been sent to the owner.",
    apartmentTag: "APARTMENT",
    yourDetailsTitle: "YOUR DETAILS",
    nameLabel: "NAME",
    phoneLabel: "PHONE",
    emailLabel: "EMAIL",
    backToHomeBtn: "Back to Home",
    viewMoreBtn: "View More Properties",

    // Inquiry Modal
    inquiryModalTitle: "Send Inquiry",
    inquiryModalTo: "to ",
    perMonthShort: "/mo",
    yourPhoneNum: "Your Phone Number",
    phoneShortError: "Looks short — please enter a full mobile number.",
    aiSuggestionsTitle: "AI Suggestions",
    aiAdded: "added",
    aiSuggestText1: "Tap to add ready-made questions to your message. We recommend at least",
    aiSuggestText2: "three",
    aiSuggestText3: "so the landlord can answer in one go.",
    yourMessage: "Your Message",
    chars: "chars",
    messageOptionalNote: "Optional — add your own note. AI questions you tap above will be appended automatically.",
    typicallyRespondsIn: "typically responds in ",
    sending: "Sending...",
    inquirySentTitle: "Inquiry sent!",
    inquirySentDesc1: "We've shared your message with ",
    inquirySentDesc2: ".",
    inquirySentDesc3: "They'll call or text ",
    inquirySentDesc4: "shortly.",
    whatHappensNext: "What happens next",
    reviewsYourMessage: "reviews your message",
    reachOutOn: "They reach out on",
    scheduleVisitStep: "Schedule a property visit",
    doneBtn: "Done",
    backToPropBtn: "Back to property",
    inquiryLoginError: "Please login first to send an inquiry.",
    inquiryFailError: "Failed to send inquiry. Please try again later.",
    aiChipRentReq: "Negotiate rent",
    aiChipRentMsg: "Hi! I'm interested in your property. Is there any flexibility on the monthly rent of {price}? I am looking to pay around [Your budget], especially if I sign for a [Lease duration] lease.",
    aiChipFacilReq: "Confirm facilities",
    aiChipFacilMsg: "Could you confirm what's included with the property? I specifically wanted to know about [Your question].",
    aiChipLocReq: "Location & access",
    aiChipLocMsg: "How accessible is {location}? I'd like to know roughly how far the property is from [Your destination].",
    aiChipVisitReq: "Schedule a visit",
    aiChipVisitMsg: "When could I come by for a tour? I am available on [Your available days/times].",
    aiChipMoveReq: "Move-in & lease",
    aiChipMoveMsg: "What's the earliest move-in date, and what's the minimum lease length? I am looking to move in around [Your move-in date].",
    aiChipSpecReq: "Confirm spec",
    aiChipSpecMsg: "Just to confirm — the listing says {parts}. Could you also share photos or a quick video walkthrough of [Specific room/area] before I visit?",
    listedRentFallback: "the listed rent",
    thisAreaFallback: "this area",
    bedLabel: "bed",
    bathLabel: "bath",
    sqftLabel: "sqft",

    // Auth Page
    welcomeBack: "Welcome Back!",
    createAccount: "Create Account",
    tenantRole: "Tenant",
    landlordRole: "Landlord",
    passPlaceholder: "Enter your password",
    namePlaceholder: "Full Name",
    forgotPass: "Forgot Password?",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    signUpNow: "Sign Up Now",
    loginNow: "Login Now",

    // Host Dashboard
    hostPortal: "Host Portal",
    managingLiving: "Managing Urban Living",
    newListing: "+ New Listing",
    dashboardMenu: "Dashboard",
    myProperties: "My Properties",
    inquiriesMenu: "Inquiries",
    bookings: "Bookings",
    earnings: "Earnings",
    settings: "Settings",
    supportMenu: "Support",
    portfolioOverview: "Portfolio Overview",
    managePremium: "Manage your premium properties in Dhaka.",
    totalProperties: "TOTAL PROPERTIES",
    totalInquiries: "TOTAL INQUIRIES",
    thisWeek: "this week",
    currentPortfolio: "Current Portfolio",
    filterBtn: "Filter",
    sortBtn: "Sort",
    activeBadge: "ACTIVE",
    rentedBadge: "RENTED",
    editBtn: "Edit",
    pauseBtn: "Pause",
    viewLeaseBtn: "View Lease",

    // Saved Properties
    savedTitle: "Saved Properties",
    savedSubtitle: "Your favorite picks, ready when you are.",
    removeBtn: "Remove",
    inquireNowBtn: "Inquire Now",
    exploreMore: "Explore More",

    // List Property
    listTitle: "List Your Property",
    step1Title: "Basic Info",
    step2Title: "Details",
    step3Title: "Amenities",
    step4Title: "Photos",
    step5Title: "Pricing",
    propTitle: "Property Title",
    propAddress: "Full Address",
    nextBtn: "Next Step",
    backBtn: "Back",
    submitListBtn: "Publish Listing",
    monthlyRent: "Monthly Rent (৳)",

    // Search UI labels
    typeLabel: "Type",
    budgetLabel: "Budget",
    popular: "Popular",
    popularAreas: "Popular Areas",
    useCurrentLocation: "Use current location",
    allAreas: "All Areas",
    suggestions: "Suggestions",
    matchingSuggestions: "Matching Suggestions",
    browseAllAreas: "Browse All Areas",
    customRange: "Custom Range (BDT)",
    applyRange: "Apply Range",
    searchProperties: "Search Properties",
    searchFor: "Search for",

    // Location search modal
    locSearchTitle: "Search location",
    locSearchPlaceholder: "Search city, area, or property…",
    locSearchStartTyping: "Start typing an area or city",
    locSearchStartTypingSub: "Matching locations appear as you type",
    locSearchNoResults: "No results found",
    locSearchClose: "Close",
    locSearchClear: "Clear",

    // Trust badges
    verifiedHosts: "Verified Hosts",
    instantBooking: "Instant Booking",
    support247: "24/7 Support",

    // App promo banner
    limitedTimeOffer: "Limited Time Offer",
    promoBannerTitle: "Find your dream home 10× faster",
    promoBannerDesc: "Download the TO-LET PRO app and get instant alerts when a property matching your criteria goes live. Zero brokerage fees.",
    availableOn: "Available on",
    priceLabel: "Price",
    getApp: "Get the App",

    // Popular divisions slider
    exploreDivisions: "Explore Divisions",
    exploreDivisionsDesc: "Discover properties across all major cities",

    // Host promo banner
    premiumHostOffer: "Premium Host Offer",
    hostBannerTitle: "List your property today and get 50% off premium placement",
    hostBannerDesc: "Join the fastest growing real estate network in Bangladesh. Verified leads, instant booking, and dedicated host support.",
    claimOfferNow: "Claim Offer Now",

    // Dhaka's Finest
    dhakasFinestDesc: "Premium living spaces in top-tier neighborhoods",
    exploreAll: "Explore All",
    avgRent: "Avg. Rent",

    // Social proof / Powered by Trust
    trustedByBD: "Trusted by Bangladesh",
    poweredByTrust: "Powered by Trust",
    poweredByTrustDesc: "The largest, most secure, and technologically advanced property rental network in Bangladesh — loved by real people.",
    statActiveUsers: "Active Users",
    statVerifiedHomes: "Verified Homes",
    statAppRating: "App Rating",
    nationwideNetworkSub: "Nationwide network",
    growingDaily: "And growing daily",
    zeroFakeListings: "Zero fake listings",
    reviewsCount: "12,000+ reviews",
    overallRating: "Overall Rating",
    basedOnReviews: "Based on 12,400+ verified reviews",
    appStore: "App Store",
    googlePlay: "Google Play",
    smartAITitle: "Smart AI-Powered Search",
    smartAIDesc: "Our NLP engine learns your preferences and surfaces the exact homes you'd love — before you even finish typing.",
    happyUsers: "+1M happy users",

    // Testimonials
    testimonial1Name: "Farhan Ahmed",
    testimonial1Role: "Software Engineer · Dhaka",
    testimonial1Badge: "Found home in 2 days",
    testimonial1Text: "I moved to Dhaka for work and found a perfect furnished apartment in Banani within two days. The verified host feature gave me so much confidence — no broker, no hassle.",
    testimonial1Area: "Banani, Dhaka",
    testimonial1Type: "Family Apartment",
    testimonial2Name: "Nusrat Jahan",
    testimonial2Role: "University Student · Chittagong",
    testimonial2Badge: "Saved ৳15,000 in fees",
    testimonial2Text: "As a female student, safety was my top priority. TO-LET PRO showed only verified female-friendly sublets. The live chat with hosts before visiting was a game-changer.",
    testimonial2Area: "GEC Circle, Chattogram",
    testimonial2Type: "Sublet Room",
    testimonial3Name: "Rakibul Islam",
    testimonial3Role: "Entrepreneur · Sylhet",
    testimonial3Badge: "Office found in 1 week",
    testimonial3Text: "Listed my commercial space and got three serious inquiries the same day. The platform is incredibly professional. I've recommended it to every business owner I know.",
    testimonial3Area: "Zindabazar, Sylhet",
    testimonial3Type: "Commercial Space",

    // Footer
    exploreFooter: "Explore",
    legalFooter: "Legal",
    contactUs: "Contact Us",
    allProperties: "All Properties",
    popularDistrictsFooter: "Popular Districts",
    commercialSpaces: "Commercial Spaces",
    hostDashboard: "Host Dashboard",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    trustSafety: "Trust & Safety",
    refundPolicy: "Refund Policy",
    builtInBD: "Built with love in Bangladesh",

    // Dictionaries
    cities: { chittagong: "Chittagong", dhaka: "Dhaka", sylhet: "Sylhet", rajshahi: "Rajshahi", khulna: "Khulna", barishal: "Barishal", rangpur: "Rangpur", mymensingh: "Mymensingh" },
    cityTags: { chittagong: "Port City", dhaka: "Premier Capital", sylhet: "Nature Hub", rajshahi: "Education City", khulna: "Industrial Hub", barishal: "River City", rangpur: "Heritage", mymensingh: "Cultural Hub" },
    districtNames: { dhanmondi: "Dhanmondi", gulshan: "Gulshan", banani: "Banani", bashundhara: "Bashundhara", mirpur: "Mirpur", mohammadpur: "Mohammadpur" },
    divisions: { Dhaka: ["Dhaka", "Gazipur", "Narayanganj"], Chittagong: ["Chattogram", "Cox's Bazar", "Comilla"], Sylhet: ["Sylhet", "Moulvibazar"], Rajshahi: ["Rajshahi", "Bogura"], Khulna: ["Khulna", "Jashore"], Barishal: ["Barishal", "Bhola"], Rangpur: ["Rangpur", "Dinajpur"], Mymensingh: ["Mymensingh", "Jamalpur"] },

    // ─── Mobile Home (mobile/MobileHome.jsx) ──────────────────────────────
    mobHeroLine1: "Find Your Next",
    mobHeroLine2: "Perfect Home",
    mobHeroSubtitle: "Verified hosts. Zero brokerage. Trusted by 1M+ Bangladeshis.",
    mobSearchAnywhere: "Search Anywhere",
    mobLocationLabel: "Location",
    mobLocationPlaceholderRent: "Where do you want to live?",
    mobLocationPlaceholderBuy: "Search city, neighborhood, or property to buy…",
    mobLocationPlaceholderCommercial: "Search commercial zone, building, or landmark…",
    mobMatchingSuggestions: "Matching suggestions",
    mobNoMatches: "No matches. Try a different area.",
    mobTypeLabel: "Type",
    mobBudgetLabel: "Budget",
    mobSearchProperties: "Search Properties",
    mobVerifiedHosts: "Verified hosts",
    mobSecurePrivate: "Secure & private",
    mobInstantBooking: "Instant booking",
    mobExploreDivisions: "Explore Divisions",
    mobExploreDivisionsSub: "Tap any division to see its districts",
    mobDistricts: "districts",
    mobPickDistrict: "Pick a district",
    mobViewHomes: "View homes",
    mobDivisionText: "Division",
    mobPopularAreas: "Popular Areas",
    mobPopularAreasSub: "Tap any area to see live listings",
    mobRecentlyPosted: "Recently posted",
    mobHomesIn: "Homes in",
    mobHomesPostedLast2: "homes posted in the last 2 days",
    mobHomePostedLast2: "home posted in the last 2 days",
    mobNoHomesYet: "No homes match this filter yet",
    mobNoHomesDesc: "We'll alert you the moment something lands. Try clearing the filter to see more.",
    mobClearFilters: "Clear filters",
    mobHavePropertyKicker: "Have a property?",
    mobHavePropertyTitle: "Let it out easily — list in 3 min",
    mobHavePropertySub: "Reach 50,000+ verified tenants today.",
    mobEndToEndSecured: "End-to-end secured by TO-LET PRO",
    mobNewToday: "New today",
    mobDayAgo: "day ago",
    mobDaysAgo: "days ago",
    mobMonth: "mo",
    mobBed: "bed",
    mobBath: "bath",
    mobReviews: "reviews",
    mobVerified: "VERIFIED",
    mobApartment: "APARTMENT",
    mobFamilyFlat: "FAMILY FLAT",
    mobBachelor: "BACHELOR",
    mobStudio: "STUDIO",
    mobSublet: "SUBLET",
    mobStudent: "STUDENT",
    mobPremium: "PREMIUM",
    mobHot: "HOT",
    mobWhatAreYouLookingFor: "What are you looking for?",
    rentMenu: "Rent",
    mobRentDesc: "Apartments, sublets, bachelor flats",
    buyMenu: "Buy",
    mobBuyDesc: "Houses, flats, land",
    commercialMenu: "Commercial",
    mobCommercialDesc: "Offices, shops, restaurants",
    NOT_LOGGED_IN: "You are not logged in. Please log in again.",
    NETWORK_ERROR: "Network issue — please try again later.",
    REQUEST_FAILED: "There was a problem with the request.",
    FILE_TOO_LARGE: "File is too large (max 5 MB).",
    FILE_READ_ERROR: "Problem reading the file.",
    DEMO_LOGIN_DISABLED: "Demo login is disabled.",
    INVALID_PHONE_NUMBER: "Invalid phone number. Enter 10 digits without +880.",
    MISSING_PHONE_NUMBER: "Please enter a phone number.",
    QUOTA_EXCEEDED: "Daily SMS limit exceeded. Use test numbers or upgrade plan.",
    CAPTCHA_CHECK_FAILED: "reCAPTCHA check failed. Please reload and try again.",
    TOO_MANY_REQUESTS: "Too many attempts. Please try again later.",
    INVALID_OTP: "Incorrect OTP code.",
    OTP_EXPIRED: "OTP code expired. Please request a new one.",
    RECAPTCHA_SETUP_ERROR: "reCAPTCHA setup problem. Please reload the page.",
    OTP_PROCESS_ERROR: "There was a problem with the OTP process.",
    UPLOAD_FAILED: "Upload failed.",
    no_file: "No file was found.",

    // ── Chat / Call / Notification UI (messaging overhaul) ─────────────────
    chatViewContact: "View contact",
    chatMute: "Mute notifications",
    chatUnmute: "Unmute notifications",
    chatReport: "Report",
    chatBlock: "Block",
    chatUnblock: "Unblock",
    chatUnblockShort: "Unblock",
    chatYouBlocked: "You blocked",
    chatCantReply: "You can't send messages to this contact.",
    chatActiveNow: "Active now",
    chatForwarded: "Message forwarded",
    chatForwardFailed: "Forward failed. Please try again.",
    chatDeleteFailed: "Could not delete the message.",
    chatRemovedForYou: "Removed for you",
    chatCopied: "Copied",
    chatPinned: "Message pinned",
    chatUnpinned: "Message unpinned",
    chatActionFailed: "Action failed. Please try again.",
    chatPinnedLabel: "Pinned",
    chatUnpin: "Unpin",
    chatForwardTo: "Forward to…",
    chatNoForwardTargets: "No other chats to forward to.",
    chatSayHiTo: "Say hi to",
    chatAskAnything: "Ask me anything",
    chatTypeMessage: "Type a message…",
    chatAskAI: "Ask the AI assistant anything…",
    chatMessages: "Messages",
    chatCalls: "Calls",
    chatChatsTab: "Chats",
    chatCallsTab: "Calls",
    chatSearchChats: "Search chats…",
    chatSearchCalls: "Search calls…",

    notifTitle: "Notifications",
    notifMarkAllRead: "Mark all read",
    notifClearAll: "Clear all",
    notifEmpty: "You're all caught up.",
    notifRemove: "Remove",
    notifSwipeHint: "Swipe a card left or right to remove",
    loading: "Loading…",

    contactInfo: "Contact info",
    contactCall: "Call",
    contactVideo: "Video",
    contactProfile: "Profile",
    contactSharedMedia: "Media, links and docs",
    contactLockPin: "Lock chat with PIN",
    contactRemovePin: "Remove PIN lock",
    contactOn: "On",
    contactOff: "Off",
    contactBlockName: "Block",
    contactReportName: "Report",

    mediaTitle: "Media, links and docs",
    mediaTabMedia: "Media",
    mediaTabLinks: "Links",
    mediaTabDocs: "Docs",
    mediaNoPhotos: "No photos or videos yet.",
    mediaNoLinks: "No links or voice messages yet.",
    mediaNoDocs: "No documents or PDFs yet.",
    mediaVoiceMessages: "Voice messages",
    mediaLinks: "Links",

    msgReply: "Reply",
    msgForward: "Forward",
    msgCopy: "Copy",
    msgPin: "Pin",
    msgUnpin: "Unpin",
    msgMute: "Mute",
    msgUnmute: "Unmute",
    msgRemove: "Remove",

    chatDeleteConversation: "Delete conversation",
    chatDeleteConfirm: "Delete this conversation?",
    chatDelete: "Delete",
    chatConversationDeleted: "Conversation deleted",
    attachPhotoVideo: "Photo & Video",
    attachDocument: "Document",
    attachTitle: "Attach photo, video or PDF",
    notifNewMessage: "New message",
    quickReplyPlaceholder: "Reply…",
    quickReplySent: "Reply sent",

    callRinging: "Ringing…",
    callCalling: "Calling…",
    callIncoming: "Incoming call",
    callVideoCall: "Video Call",
    callVoiceCall: "Voice Call",
    callMuted: "You are muted",
    callDecline: "Decline",
    callAccept: "Accept",
    callCancel: "Cancel",
    callMute: "Mute",
    callUnmute: "Unmute",
    callCamera: "Camera",
    callCameraOn: "Turn camera on",
    callCameraOff: "Turn camera off",
    callEnd: "End",
    callFlip: "Flip",
    callFlipCamera: "Flip camera",
    callMissedTitle: "Missed call",
    callEndedTitle: "Call ended",
    callDeclinedTitle: "Call declined",
    callBusyTitle: "Call declined",
    callCancelledTitle: "Call cancelled",
    callFailedTitle: "Call failed",
    callFailedSub: "Couldn't connect the call",
    callBackAction: "Call back",
    callNoLongerActive: "Call no longer active",
  },

  'বাংলা': {
    // Navbar & Hero
    brand: "টু-লেট প্রো", 
    business: "ব্যবসা", 
    listProperty: "বাড়ি দিন", 
    login: "লগইন / সাইনআপ", 
    allCities: "সব শহর",
    findYourNext: "খুঁজে নিন আপনার", 
    sweetHome: "স্বপ্নের ঠিকানা",

    // ─── Mobile menu drawer (Navbar.jsx) ───
    menuJoinTitle: "টু-লেট প্রো-তে যোগ দিন",
    menuJoinSubtitle: "ড্যাশবোর্ড, সেভ করা সার্চ, অ্যালার্ট ও আরও অনেক কিছু",
    menuLogIn: "লগইন",
    menuSignUp: "সাইন আপ",
    menuTenantDashboard: "ভাড়াটিয়া ড্যাশবোর্ড",
    menuHostDashboard: "বাড়িত্তয়ালা ড্যাশবোর্ড",
    menuSavedProperties: "সেভ করা বাড়ি",
    menuMyInquiries: "আমার যোগাযোগ",
    menuMyAlerts: "আমার অ্যালার্ট",
    menuAddProperty: "বাড়ি যোগ করুন",
    menuListingAnalytics: "লিস্টিং অ্যানালিটিক্স",
    menuTenantMessages: "ভাড়াটিয়ার বার্তা",
    menuSearchProperties: "বাসা খুঁজুন",
    menuListProperty: "বাসা যোগ করুন",
    menuSwitchToHost: "বাড়িত্তয়ালা মোডে যান",
    menuSwitchToTenant: "ভাড়াটিয়া মোডে যান",
    menuHostModeActive: "হোস্ট মোড চালু",
    menuTenantModeActive: "ভাড়াটিয়া মোড চালু",
    menuRoleHost: "হোস্ট",
    menuRoleTenant: "ভাড়াটিয়া",
    menuBecomeLandlord: "আমি বাড়িওয়ালা হতে চাই",
    menuBecomeLandlordSub: "আপনার বাড়ি ভাড়া দিন",
    menuBecomeLandlordCta: "শুরু",
    menuHelpSupport: "সহায়তা ও সাপোর্ট",
    menuSettings: "সেটিংস",
    menuTermsPolicies: "শর্তাবলী ও নীতিমালা",
    menuLanguageLabel: "ভাষা",
    menuLogOut: "লগ আউট",
    menuSectionAccount: "আমার অ্যাকাউন্ট",
    menuSectionExplore: "খুঁজে দেখ",
    menuSectionSupport: "সহায়তা",
    navPricing: "মূল্য",
    navHelp: "সহায়তা",
    navLogIn: "লগইন",
    navSignUp: "সাইন আপ",
    navImLandlord: "আমি বাড়িওয়ালা",

    // Hero Section
    heroTagline: "বাংলাদেশের ১নং বাড়ি প্ল্যাটফর্ম",
    heroTitle1: "খুঁজে নিন আপনার",
    heroTitle2: "স্বপ্নের ঠিকানা",
    heroSubtext: "১০০% ভেরিফাইড হোস্টদের সাথে ঢাকা ও সারা বাংলাদেশের সেরা সব অ্যাপার্টমেন্ট, ডুপ্লেক্স এবং কমার্শিয়াল স্পেস খুঁজে নিন।",
    tabRent: "ভাড়া",
    tabBuy: "ক্রয়",
    tabCommercial: "বাণিজ্যিক",
    tabResidential: "আবাসিক",
    searchLocation: "লোকেশন",
    locationPlaceholder: "কোথায় থাকতে চান?",
    locationPlaceholderBuy: "শহর, এলাকা বা প্রপার্টি…",
    locationPlaceholderCommercial: "এলাকা, ভবন বা ল্যান্ডমার্ক…",
    searchType: "বাড়ির ধরন",
    searchBudget: "বাজেট",
    searchBtn: "খুঁজুন",
    typeAny: "যেকোনো বাড়ি",
    typeApt: "অ্যাপার্টমেন্ট",
    typeDuplex: "ডুপ্লেক্স",
    typeStudio: "স্টুডিও",
    budgetAny: "বাজেট নির্বাচন করুন",
    budgetLow: "২০ হাজার এর নিচে",
    budgetMid: "২০ হাজার - ৫০ হাজার",
    budgetHigh: "৫০ হাজার - ১ লাখ",
    budgetPremium: "১ লাখ এর ওপরে",
    
    // Browse By Location Section
    premiumLocations: "প্রিমিয়াম লোকেশন",
    browseBy: "খুঁজুন আপনার",
    locationText: "পছন্দের শহরে",
    viewFeatured: "প্রধান শহরগুলো দেখুন",
    viewAllCities: "সব শহর দেখুন",
    listings: "টি বাড়ি",

    // Popular Locations Section
    primeLocations: "প্রাইম লোকেশন",
    dhakasFinest: "ঢাকার সেরা",
    districts: "এলাকাসমূহ",
    districtsDesc: "আধুনিক পেশাজীবী এবং পারিবারিক জীবনের জন্য বাছাইকৃত প্রিমিয়াম আবাসিক এলাকা।",
    viewAllNeighborhoods: "সব এলাকা দেখুন",
    viewLess: "কম দেখান",
    premiumListings: "টি প্রিমিয়াম লিস্টিং",
    
    // Uttara Banner
    uttaraSectors: "উত্তরা সেক্টরস",
    uttaraDesc: "পরিকল্পিত লেআউট, বিমানবন্দর এবং প্রস্তাবিত মেট্রো রেলের সাথে চমৎকার যোগাযোগ ব্যবস্থাসম্পন্ন অনন্য আবাসিক এলাকা।",
    exploreSectorListings: "সেক্টর লিস্টিং এক্সপ্লোর করুন",

    // Stats Section
    dhakaCentral: "মধ্য ঢাকা",
    sylhetHills: "সিলেটের পাহাড়",
    chittagongPort: "চট্টগ্রাম বন্দর",
    nationwideNetwork: "দেশব্যাপী নেটওয়ার্ক",
    statsTitle1: "টু-লেট আছে আপনার",
    statsTitleAround: "আশেপাশেই।",
    statsTitleAlways: "সবসময়।",
    statsDesc: "দেশব্যাপী বিস্তৃত আমাদের নেটওয়ার্ক। শহরের বিলাসবহুল ফ্ল্যাট হোক বা শহরতলির শান্ত ভিলা, সব চাবি আছে আমাদের কাছে।",
    districtsCovered: "জেলা কভার করা হয়েছে",
    activeListings: "অ্যাক্টিভ লিস্টিং",
    divisionText: "বিভাগ",

    // CTA Section
    joinFuture: "ভাড়ার ভবিষ্যৎ এর সাথে যুক্ত হোন",
    readyToList: "আপনার বাড়ি ভাড়া দিতে",
    spaceText: "প্রস্তুত?",
    ctaDesc: "৫,০০০+ বিশ্বস্ত ল্যান্ডলর্ডদের সাথে যুক্ত হোন যারা ইতিমধ্যেই বাংলাদেশের সবচেয়ে প্রিমিয়াম রেন্টাল প্ল্যাটফর্মের মাধ্যমে সঠিক ভাড়াটিয়া খুঁজে পেয়েছেন।",
    getStartedFree: "ফ্রি-তে শুরু করুন",
    learnMoreBtn: "আরও জানুন",

    // Footer Section
    footerDesc: "বাছাইকৃত প্রিমিয়াম লিস্টিং এবং আধুনিক প্রযুক্তির মাধ্যমে বাংলাদেশের রেন্টাল অভিজ্ঞতাকে অনন্য উচ্চতায় নিয়ে যাওয়া।",
    discoveryTitle: "ডিসকভারি",
    navNewListings: "নতুন লিস্টিং",
    navPopularAreas: "জনপ্রিয় এলাকা",
    navAffordableStudios: "সাশ্রয়ী স্টুডিও",
    navLuxuryFlats: "লাক্সারি ফ্ল্যাট",
    landlordsTitle: "ল্যান্ডলর্ডদের জন্য",
    navHowItWorks: "কীভাবে কাজ করে",
    navListProperty: "বাড়ি দিন",
    navTrustSafety: "বিশ্বাস ও নিরাপত্তা",
    navHostGuidelines: "হোস্ট গাইডলাইন",
    stayInspired: "অনুপ্রাণিত থাকুন",
    newsletterDesc: "বাছাইকৃত বাড়ির সুপারিশ পেতে আমাদের নিউজলেটারে যুক্ত হোন।",
    emailPlaceholder: "আপনার ইমেইল দিন",
    footerCopyright: "© ২০২৬ টু-লেট প্রো। সর্বস্বত্ব সংরক্ষিত।",
    privacyPolicyUpper: "গোপনীয়তা নীতি",
    termsServiceUpper: "শর্তাবলী",
    cookiesUpper: "কুকিজ",

    // Filters & Property Listing
    activeFilters: "অ্যাক্টিভ ফিল্টার",
    clearAll: "সব মুছুন",
    sortNewest: "নতুন লিস্টিং",
    sortPriceLowHigh: "দাম: কম → বেশি",
    sortPriceHighLow: "দাম: বেশি → কম",
    sortPopular: "সবচেয়ে জনপ্রিয়",
    filtersBtn: "ফিল্টার",
    advancedFilter: "অ্যাডভান্সড",
    filterWord: "ফিল্টার",
    bangladesh: "বাংলাদেশ",
    filterLocation: "এলাকা",
    searchWithin: "খুঁজুন",
    filterPrice: "ভাড়ার বাজেট",
    minPrice: "সর্বনিম্ন ভাড়া",
    maxPrice: "সর্বোচ্চ ভাড়া",
    filterPropType: "বাসার ধরন",
    propApartment: "ফ্ল্যাট / অ্যাপার্টমেন্ট",
    propIndependent: "আলাদা বাসা",
    propDuplex: "ডুপ্লেক্স বাসা",
    propStudio: "স্টুডিও ফ্ল্যাট",
    propPenthouse: "পেন্টহাউস",
    filterRooms: "রুম ও বাথরুম",
    bedrooms: "শোবার রুম",
    bathrooms: "বাথরুম",
    bathroomType: "বাথরুম",
    any: "যেকোনো",
    attachedBath: "নিজস্ব বাথরুম",
    sharedBath: "শেয়ার বাথরুম",
    filterSize: "জায়গা (স্কয়ার ফিট)",
    maxSize: "সর্বোচ্চ জায়গা:",
    filterUtilities: "অন্তর্ভুক্ত ইউটিলিটি বিল",
    waterBill: "পানি",
    electricityBill: "বিদ্যুৎ বিল",
    gasSupply: "গ্যাস সংযোগ",
    internetWifi: "ইন্টারনেট / ওয়াইফাই",
    serviceCharge: "সার্ভিস চার্জ",
    filterTenant: "ভাড়াটিয়ার ধরন ও বিবরণ",
    tenantType: "ভাড়াটিয়া ধরন",
    family: "পরিবার",
    bachelor: "ব্যাচেলর",
    students: "ছাত্র-ছাত্রী",
    petsAllowed: "পোষা প্রাণী অনুমোদিত",
    // Rental category labels (shared by chip group on the listing page)
    filterWhoMovesIn: "ভাড়াটিয়া ধরন",
    catFamilyFlat: "পরিবার (ফ্ল্যাট)",
    catBachelorMale: "ব্যাচেলর (ছেলে)",
    catBachelorFemale: "ব্যাচেলর (মেয়ে)",
    catSubletRoom: "সাবলেট / রুম",
    catStudent: "ছাত্র-ছাত্রী",
    // Quick budget pills shown above the price slider
    quickBudgetLabel: "দ্রুত বাজেট",
    budgetUpto15k: "১৫k এর নিচে",
    budgetUpto25k: "১৫k–২৫k",
    budgetUpto40k: "২৫k–৪০k",
    budgetUpto60k: "৪০k–৬০k",
    budgetAbove60k: "৬০k এর উপরে",
    furnishing: "আসবাবপত্র",
    furnished: "আসবাবপত্রসহ",
    semiFurnished: "কিছু আসবাবসহ",
    unfurnished: "আসবাবপত্র ছাড়া",
    filterAmenities: "অন্যান্য সুযোগ-সুবিধা",
    amenities: "সুযোগ-সুবিধা",
    parking: "গাড়ি পার্কিং",
    elevator: "লিফট",
    generator: "জেনারেটর",
    securityCctv: "সিসিটিভি / নিরাপত্তা",
    ac: "এসি",
    floorLevel: "ফ্লোর/তলা",
    anyFloor: "যেকোনো তলা",
    groundFloor: "নিচতলা",
    floor1to3: "১ম–৩য় তলা",
    floor4to7: "৪র্থ–৭ম তলা",
    floor8Plus: "৮ম তলা বা উপরে",
    filterFinancials: "জামানত ও প্রবেশকাল",
    depositAdvance: "অগ্রিম জামানত",
    noAdvance: "অগ্রিম প্রযোজ্য নয়",
    monthAdvance1: "১ মাসের জামানত",
    monthAdvance2: "২ মাসের জামানত",
    negotiableDeposit: "আলোচনা সাপেক্ষে",
    availability: "প্রবেশের সময়কাল",
    availableNow: "তাৎক্ষণিক প্রবেশযোগ্য",
    availableThisMonth: "চলতি মাসে",
    availableNextMonth: "আগামী মাসে",
    filterRating: "বাসার রেটিং",
    star4Above: "৪.০ ও তার উপরে",
    star3Above: "৩.০ ও তার উপরে",
    anyRating: "যেকোনো রেটিং",
    applyFiltersBtn: "ফিল্টার দেখান",
    searchAreaPlaceholder: "এলাকার নাম লিখুন...",
    nearMe: "আমার কাছাকাছি",
    locating: "খুঁজছে...",
    showing: "দেখাচ্ছে",
    backToTop: "ওপরে যান",
    home: "হোম",
    sortBy: "সাজান:",
    reviews: "রিভিউ",
    inquiriesToday: "আজকের যোগাযোগ",
    off: "ছাড়",
    perMonthExcluding: "প্রতি মাস • ইউটিলিটি বাদে",
    detailsBtn: "বিস্তারিত",
    clearFilters: "ফিল্টার মুছুন",

    // Property Card & Details
    properties: "বাড়িসমূহ",
    verified: "ভেরিফাইড",
    monthlyRentText: "মাসিক ভাড়া",
    inquireBtn: "যোগাযোগ করুন",
    beds: "বেড",
    baths: "বাথ",
    sqft: "বর্গফুট",
    noPropsFound: "কোনো বাড়ি পাওয়া যায়নি",
    noPropsDesc: "এর জন্য কোনো লিস্টিং পাওয়া যায়নি।",
    adjustFilters: "আপনার ফিল্টার পরিবর্তন করে দেখুন।",
    backToResults: "সার্চে ফিরে যান",
    aboutProperty: "এই বাড়ি সম্পর্কে",
    propertyDesc: "শহরের প্রাণকেন্দ্রে অতুলনীয় বিলাসবহুল অভিজ্ঞতার স্বাদ নিন।",
    amenitiesTitle: "সুযোগ-সুবিধা",
    propDetailsTitle: "বাড়ির বিবরণ",
    listedBy: "লিস্টিং করেছেন",
    viewProfile: "প্রোফাইল দেখুন",
    callNow: "কল করুন",
    messageBtn: "মেসেজ দিন",
    requestDetails: "রিকোয়েস্ট ডিটেইলস",
    yourName: "আপনার নাম",
    phoneNum: "ফোন নম্বর",
    messageLabel: "মেসেজ",
    defaultMsg: "আমি এই বাড়িটি ভাড়া নিতে আগ্রহী।",
    submitInquiry: "যোগাযোগ জমা দিন",
    share: "শেয়ার",
    save: "সেভ করুন",
    availableImmed: "তাৎক্ষণিক প্রবেশযোগ্য",
    monthText: "মাস",
    offText: "ছাড়",
    inquireTitle: "এই বাড়ি সম্পর্কে যোগাযোগ করুন",
    inquireSubtitle: "আপনার তথ্য এজেন্টকে পাঠান।",
    priceSummary: "ভাড়ার বিবরণ",
    baseRent: "মূল ভাড়া",
    promoDiscount: "প্রোমোশনাল ছাড়",
    finalPrice: "মোট ভাড়া",
    fullName: "সম্পূর্ণ নাম",
    emailAddress: "ইমেইল অ্যাড্রেস",
    moveInDate: "প্রবেশের কাঙ্ক্ষিত তারিখ",
    msgToAgent: "এজেন্টকে বার্তা পাঠান",
    scheduleVisit: "বাড়ি পরিদর্শন",
    requestCallback: "কলব্যাক অনুরোধ",
    sendInquiry: "যোগাযোগ পাঠান",
    verifiedProperty: "ভেরিফাইড বাড়ি",
    docsChecked: "টু-লেট প্রো দ্বারা যাচাইকৃত।",
    secureInquiry: "সুরক্ষিত যোগাযোগ",
    dataPrivate: "আপনার তথ্য নিরাপদ থাকবে।",
    fastResponse: "দ্রুত রেসপন্স",
    agentNotified: "এজেন্টকে সাথে সাথে জানানো হয়।",
    typicallyReplies: "সাধারণত ১ ঘণ্টার মধ্যে রিপ্লাই দেয়",

    // Success Page
    successMainTitle: "যোগাযোগ সফলভাবে পাঠানো হয়েছে!",
    successSubText: "আপনার রিকোয়েস্ট বাড়ির মালিকের কাছে পাঠানো হয়েছে।",
    apartmentTag: "অ্যাপার্টমেন্ট",
    yourDetailsTitle: "আপনার বিস্তারিত তথ্য",
    nameLabel: "নাম",
    phoneLabel: "ফোন",
    emailLabel: "ইমেইল",
    backToHomeBtn: "হোমে ফিরে যান",
    viewMoreBtn: "আরও বাড়ি দেখুন",

    // Inquiry Modal
    inquiryModalTitle: "ইনকোয়ারি পাঠান",
    inquiryModalTo: "প্রতি ",
    perMonthShort: "/মাস",
    yourPhoneNum: "আপনার মোবাইল নম্বর",
    phoneShortError: "নম্বরটি ছোট মনে হচ্ছে — অনুগ্রহ করে সম্পূর্ণ নম্বর দিন।",
    aiSuggestionsTitle: "এআই সাজেশন",
    aiAdded: "যোগ করা হয়েছে",
    aiSuggestText1: "আপনার বার্তায় প্রস্তুত করা প্রশ্ন যোগ করতে ট্যাপ করুন। আমরা অন্তত",
    aiSuggestText2: "৩টি",
    aiSuggestText3: "সুপারিশ করছি যাতে মালিক একবারে উত্তর দিতে পারেন।",
    yourMessage: "আপনার বার্তা",
    chars: "অক্ষর",
    messageOptionalNote: "ঐচ্ছিক — আপনার নিজস্ব নোট যোগ করুন। উপরে ট্যাপ করা এআই প্রশ্নগুলো স্বয়ংক্রিয়ভাবে যুক্ত হবে।",
    typicallyRespondsIn: "সাধারণত উত্তর দেন ",
    sending: "পাঠানো হচ্ছে...",
    inquirySentTitle: "ইনকোয়ারি পাঠানো হয়েছে!",
    inquirySentDesc1: "আমরা আপনার বার্তা শেয়ার করেছি ",
    inquirySentDesc2: " এর সাথে।",
    inquirySentDesc3: "তারা শীঘ্রই আপনাকে কল বা টেক্সট করবে ",
    inquirySentDesc4: " নম্বরে।",
    whatHappensNext: "এরপর কী হবে",
    reviewsYourMessage: "আপনার বার্তা দেখবেন",
    reachOutOn: "তারা যোগাযোগ করবেন",
    scheduleVisitStep: "প্রপার্টি ভিজিট শিডিউল করবেন",
    doneBtn: "সম্পন্ন",
    backToPropBtn: "প্রপার্টিতে ফিরে যান",
    inquiryLoginError: "Inquiry পাঠাতে আগে লগইন করুন।",
    inquiryFailError: "Inquiry পাঠাতে সমস্যা হয়েছে। পরে আবার চেষ্টা করুন।",
    aiChipRentReq: "ভাড়া কমানোর অনুরোধ",
    aiChipRentMsg: "আসসালামু আলাইকুম! আমি আপনার প্রপার্টিটিতে আগ্রহী। {price} ভাড়া কি কিছুটা কমানো সম্ভব? আমি [আপনার প্রস্তাবিত ভাড়া] দিতে আগ্রহী, বিশেষ করে যদি আমি [চুক্তির মেয়াদ] মেয়াদী চুক্তিতে থাকি।",
    aiChipFacilReq: "সুবিধাগুলো নিশ্চিত করুন",
    aiChipFacilMsg: "অনুগ্রহ করে নিশ্চিত করবেন কি প্রপার্টিটিতে গ্যাস, পানি, পার্কিং, লিফট, জেনারেটর এবং ইন্টারনেট সুবিধা আছে কিনা? আমি জানতে চাচ্ছিলাম [আপনার প্রশ্ন লিখুন] সম্পর্কে।",
    aiChipLocReq: "অবস্থান ও যাতায়াত",
    aiChipLocMsg: "{location} যাতায়াতের সুবিধা কেমন? আমি জানতে চাই প্রপার্টিটি থেকে নিকটস্থ [আপনার গন্তব্য] কতটা দূরে।",
    aiChipVisitReq: "ভিজিটের সময় নির্ধারণ",
    aiChipVisitMsg: "আমি কি প্রপার্টিটি দেখতে আসতে পারি? আমি [আপনার সুবিধামতো বার ও সময়] আসতে পারব — অনুগ্রহ করে আপনার সুবিধামতো একটি সময় জানান।",
    aiChipMoveReq: "ওঠার তারিখ ও চুক্তি",
    aiChipMoveMsg: "সবচেয়ে তাড়াতাড়ি কবে ওঠা যাবে এবং সর্বনিম্ন চুক্তির মেয়াদ কত? আমি [ওঠার সম্ভাব্য তারিখ] তারিখে উঠতে চাই।",
    aiChipSpecReq: "স্পেসিফিকেশন নিশ্চিত করুন",
    aiChipSpecMsg: "নিশ্চিত করার জন্য — লিস্টিং-এ বলা হয়েছে {parts}। আমি ভিজিট করার আগে আপনি কি [নির্দিষ্ট কোন ছবি/ভিডিও] পাঠাতে পারবেন?",
    listedRentFallback: "উল্লেখিত ভাড়া",
    thisAreaFallback: "এই এলাকা",
    bedLabel: "বেড",
    bathLabel: "বাথ",
    sqftLabel: "স্কয়ার ফিট",

    // Auth Page
    welcomeBack: "স্বাগতম!",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    tenantRole: "ভাড়াটিয়া",
    landlordRole: "মালিক",
    passPlaceholder: "আপনার পাসওয়ার্ড দিন",
    namePlaceholder: "সম্পূর্ণ নাম",
    forgotPass: "পাসওয়ার্ড ভুলে গেছেন?",
    noAccount: "অ্যাকাউন্ট নেই?",
    hasAccount: "আগে থেকেই অ্যাকাউন্ট আছে?",
    signUpNow: "এখনই সাইন আপ করুন",
    loginNow: "এখনই লগইন করুন",

    // Host Dashboard
    hostPortal: "হোস্ট পোর্টাল",
    managingLiving: "আরবান লিভিং ম্যানেজমেন্ট",
    newListing: "+ নতুন লিস্টিং",
    dashboardMenu: "ড্যাশবোর্ড",
    myProperties: "আমার বাড়ি",
    inquiriesMenu: "যোগাযোগ",
    bookings: "বুকিং",
    earnings: "উপার্জন",
    settings: "সেটিংস",
    supportMenu: "সাপোর্ট",
    portfolioOverview: "পোর্টফোলিও ওভারভিউ",
    managePremium: "ঢাকায় আপনার প্রিমিয়াম বাড়ি পরিচালনা করুন।",
    totalProperties: "মোট বাড়ি",
    totalInquiries: "মোট যোগাযোগ",
    thisWeek: "এই সপ্তাহে",
    currentPortfolio: "বর্তমান পোর্টফোলিও",
    filterBtn: "ফিল্টার",
    sortBtn: "সর্ট",
    activeBadge: "সক্রিয়",
    rentedBadge: "ভাড়ায় চালিত",
    editBtn: "এডিট",
    pauseBtn: "পজ",
    viewLeaseBtn: "লিজ দেখুন",

    // Saved Properties
    savedTitle: "সেভ করা বাড়ি",
    savedSubtitle: "আপনার পছন্দের তালিকা, এক নজরে।",
    removeBtn: "রিমুভ করুন",
    inquireNowBtn: "যোগাযোগ করুন",
    exploreMore: "আরও খুঁজুন",

    // List Property
    listTitle: "আপনার বাড়ি লিস্ট করুন",
    step1Title: "সাধারণ তথ্য",
    step2Title: "বিস্তারিত",
    step3Title: "সুযোগ-সুবিধা",
    step4Title: "ছবি",
    step5Title: "ভাড়া",
    propTitle: "বাড়ির নাম",
    propAddress: "সম্পূর্ণ ঠিকানা",
    nextBtn: "পরবর্তী ধাপ",
    backBtn: "পেছনে",
    submitListBtn: "পাবলিশ করুন",
    monthlyRent: "মাসিক ভাড়া (৳)",
    Inquire: "যোগাযোগ করুন",
    Inquiries: "যোগাযোগ সমূহ",
    Messages: "বার্তা",
    Support: "সহায়তা",
    Bookings: "ভাড়ার তালিকা",

    // Search UI labels
    typeLabel: "ধরন",
    budgetLabel: "বাজেট",
    popular: "জনপ্রিয়",
    popularAreas: "জনপ্রিয় এলাকা",
    useCurrentLocation: "বর্তমান লোকেশন ব্যবহার করুন",
    allAreas: "সব এলাকা",
    suggestions: "পরামর্শ",
    matchingSuggestions: "মিলে যাওয়া ফলাফল",
    browseAllAreas: "সব এলাকা দেখুন",
    customRange: "কাস্টম রেঞ্জ (৳)",
    applyRange: "রেঞ্জ প্রয়োগ করুন",
    searchProperties: "বাড়ি খুঁজুন",
    searchFor: "খুঁজুন",

    // Location search modal
    locSearchTitle: "লোকেশন খুঁজুন",
    locSearchPlaceholder: "শহর, এলাকা বা বাড়ি লিখুন…",
    locSearchStartTyping: "একটি এলাকা বা শহরের নাম লিখুন",
    locSearchStartTypingSub: "টাইপ করলেই মিলে যাওয়া লোকেশন দেখা যাবে",
    locSearchNoResults: "কোনো ফলাফল পাওয়া যায়নি",
    locSearchClose: "বন্ধ করুন",
    locSearchClear: "মুছুন",

    // Trust badges
    verifiedHosts: "ভেরিফাইড হোস্ট",
    instantBooking: "তাৎক্ষণিক বুকিং",
    support247: "২৪/৭ সাপোর্ট",

    // App promo banner
    limitedTimeOffer: "সীমিত সময়ের অফার",
    promoBannerTitle: "১০ গুণ দ্রুত খুঁজুন স্বপ্নের বাড়ি",
    promoBannerDesc: "টু-লেট প্রো অ্যাপ ডাউনলোড করুন এবং আপনার পছন্দের বাড়ি উপলব্ধ হলেই তাৎক্ষণিক নোটিফিকেশন পান। শূন্য দালাল ফি।",
    availableOn: "পাওয়া যাচ্ছে",
    priceLabel: "মূল্য",
    getApp: "অ্যাপ ডাউনলোড করুন",

    // Popular divisions slider
    exploreDivisions: "বিভাগ অন্বেষণ করুন",
    exploreDivisionsDesc: "প্রধান শহরগুলোতে বাড়ি আবিষ্কার করুন",

    // Host promo banner
    premiumHostOffer: "প্রিমিয়াম হোস্ট অফার",
    hostBannerTitle: "আজই আপনার বাড়ি লিস্ট করুন এবং ৫০% ছাড় পান",
    hostBannerDesc: "বাংলাদেশের সবচেয়ে দ্রুত বর্ধনশীল রিয়েল এস্টেট নেটওয়ার্কে যোগ দিন। ভেরিফাইড লিড, তাৎক্ষণিক বুকিং, এবং ডেডিকেটেড হোস্ট সাপোর্ট।",
    claimOfferNow: "অফার নিন এখনই",

    // Dhaka's Finest
    dhakasFinestDesc: "শীর্ষ-মানের আবাসিক এলাকায় প্রিমিয়াম বাসস্থান",
    exploreAll: "সব দেখুন",
    avgRent: "গড় ভাড়া",

    // Social proof / Powered by Trust
    trustedByBD: "বাংলাদেশের বিশ্বাস",
    poweredByTrust: "বিশ্বাসের শক্তিতে",
    poweredByTrustDesc: "বাংলাদেশের সবচেয়ে বড়, সবচেয়ে নিরাপদ এবং সবচেয়ে প্রযুক্তি-উন্নত বাড়ি রেন্টাল নেটওয়ার্ক — সত্যিকারের মানুষের পছন্দের।",
    statActiveUsers: "সক্রিয় ব্যবহারকারী",
    statVerifiedHomes: "ভেরিফাইড বাড়ি",
    statAppRating: "অ্যাপ রেটিং",
    nationwideNetworkSub: "দেশব্যাপী নেটওয়ার্ক",
    growingDaily: "প্রতিদিন বাড়ছে",
    zeroFakeListings: "কোনো ভুয়া লিস্টিং নেই",
    reviewsCount: "১২,০০০+ রিভিউ",
    overallRating: "সামগ্রিক রেটিং",
    basedOnReviews: "১২,৪০০+ যাচাইকৃত রিভিউর ভিত্তিতে",
    appStore: "অ্যাপ স্টোর",
    googlePlay: "গুগল প্লে",
    smartAITitle: "স্মার্ট AI-চালিত সার্চ",
    smartAIDesc: "আমাদের NLP ইঞ্জিন আপনার পছন্দ শিখে নেয় এবং আপনার টাইপ শেষ হওয়ার আগেই একদম সঠিক বাড়িগুলো দেখায়।",
    happyUsers: "+১০ লাখ সন্তুষ্ট ব্যবহারকারী",

    // Testimonials
    testimonial1Name: "ফারহান আহমেদ",
    testimonial1Role: "সফটওয়্যার ইঞ্জিনিয়ার · ঢাকা",
    testimonial1Badge: "২ দিনেই বাড়ি পেয়েছি",
    testimonial1Text: "কাজের জন্য ঢাকায় এসে মাত্র দুই দিনে বনানীতে একটি চমৎকার ফার্নিশড অ্যাপার্টমেন্ট পেয়েছি। ভেরিফাইড হোস্ট ফিচারটি আমাকে অনেক আত্মবিশ্বাস দিয়েছে — কোনো দালাল নেই, কোনো ঝামেলা নেই।",
    testimonial1Area: "বনানী, ঢাকা",
    testimonial1Type: "ফ্যামিলি অ্যাপার্টমেন্ট",
    testimonial2Name: "নুসরাত জাহান",
    testimonial2Role: "বিশ্ববিদ্যালয় শিক্ষার্থী · চট্টগ্রাম",
    testimonial2Badge: "৳১৫,০০০ ফি বাঁচিয়েছি",
    testimonial2Text: "মেয়ে শিক্ষার্থী হিসেবে নিরাপত্তা আমার কাছে সবচেয়ে গুরুত্বপূর্ণ ছিল। টু-লেট প্রো শুধু মেয়েদের জন্য ভেরিফাইড সাবলেট দেখিয়েছে। পরিদর্শনের আগে হোস্টের সাথে লাইভ চ্যাটের সুবিধাটি দারুণ ছিল।",
    testimonial2Area: "জিইসি সার্কেল, চট্টগ্রাম",
    testimonial2Type: "সাবলেট রুম",
    testimonial3Name: "রাকিবুল ইসলাম",
    testimonial3Role: "উদ্যোক্তা · সিলেট",
    testimonial3Badge: "১ সপ্তাহে অফিস পেয়েছি",
    testimonial3Text: "আমার কমার্শিয়াল স্পেস লিস্ট করার একই দিনে তিনটি গুরুতর যোগাযোগ পেয়েছি। প্ল্যাটফর্মটি অবিশ্বাস্য রকম পেশাদার। আমি আমার পরিচিত সব ব্যবসায়ীকে এটি সুপারিশ করেছি।",
    testimonial3Area: "জিন্দাবাজার, সিলেট",
    testimonial3Type: "বাণিজ্যিক স্থান",

    // Footer
    exploreFooter: "অন্বেষণ",
    legalFooter: "আইনি",
    contactUs: "যোগাযোগ করুন",
    allProperties: "সব বাড়ি",
    popularDistrictsFooter: "জনপ্রিয় এলাকা",
    commercialSpaces: "বাণিজ্যিক স্থান",
    hostDashboard: "হোস্ট ড্যাশবোর্ড",
    termsOfService: "শর্তাবলী",
    privacyPolicy: "গোপনীয়তা নীতি",
    trustSafety: "বিশ্বাস ও নিরাপত্তা",
    refundPolicy: "ফেরত নীতি",
    builtInBD: "ভালোবাসায় বানানো বাংলাদেশে",

    // Dictionaries
    cities: { chittagong: "চট্টগ্রাম", dhaka: "ঢাকা", sylhet: "সিলেট", rajshahi: "রাজশাহী", khulna: "খুলনা", barishal: "বরিশাল", rangpur: "রংপুর", mymensingh: "ময়মনসিংহ" },
    cityTags: { chittagong: "বন্দর নগরী", dhaka: "প্রধান রাজধানী", sylhet: "প্রকৃতির কেন্দ্র", rajshahi: "শিক্ষা নগরী", khulna: "শিল্প কেন্দ্র", barishal: "নদীর শহর", rangpur: "ঐতিহ্যবাহী", mymensingh: "সাংস্কৃতিক কেন্দ্র" },
    districtNames: { dhanmondi: "ধানমন্ডি", gulshan: "গুলশান", banani: "বনানী", bashundhara: "বসুন্ধরা", mirpur: "মিরপুর", mohammadpur: "মোহাম্মদপুর" },
    divisions: { 'ঢাকা': ["ঢাকা", "গাজীপুর", "নারায়ণগঞ্জ"], 'চট্টগ্রাম': ["চট্টগ্রাম", "কক্সবাজার", "কুমিল্লা"], 'সিলেট': ["সিলেট", "মৌলভীবাজার"], 'রাজশাহী': ["রাজশাহী", "বগুড়া"], 'খুলনা': ["খুলনা", "যশোর"], 'বরিশাল': ["বরিশাল", "ভোলা"], 'রংপুর': ["রংপুর", "দিনাজপুর"], 'ময়মনসিংহ': ["ময়মনসিংহ", "জামালপুর"] },

    // ─── Mobile Home (mobile/MobileHome.jsx) ──────────────────────────────
    mobHeroLine1: "খুঁজে নিন আপনার",
    mobHeroLine2: "স্বপ্নের ঠিকানা",
    mobHeroSubtitle: "ভেরিফাইড হোস্ট। কোনো ব্রোকারেজ নয়। ১০ লাখের বেশি মানুষের আস্থা।",
    mobSearchAnywhere: "যেকোনো জায়গায় খুঁজুন",
    mobLocationLabel: "লোকেশন",
    mobLocationPlaceholderRent: "কোথায় থাকতে চান?",
    mobLocationPlaceholderBuy: "শহর, এলাকা বা বাড়ি খুঁজুন…",
    mobLocationPlaceholderCommercial: "কমার্শিয়াল জোন, বিল্ডিং বা ল্যান্ডমার্ক খুঁজুন…",
    mobMatchingSuggestions: "মিলে যাওয়া এলাকা",
    mobNoMatches: "মিল পাওয়া যায়নি। অন্য এলাকা চেষ্টা করুন।",
    mobTypeLabel: "ধরন",
    mobBudgetLabel: "বাজেট",
    mobSearchProperties: "বাড়ি খুঁজুন",
    mobVerifiedHosts: "ভেরিফাইড হোস্ট",
    mobSecurePrivate: "সুরক্ষিত ও ব্যক্তিগত",
    mobInstantBooking: "তাৎক্ষণিক বুকিং",
    mobExploreDivisions: "বিভাগ দেখুন",
    mobExploreDivisionsSub: "জেলা দেখতে যেকোনো বিভাগে ট্যাপ করুন",
    mobDistricts: "জেলা",
    mobPickDistrict: "একটি জেলা বাছাই করুন",
    mobViewHomes: "বাসা দেখুন",
    mobDivisionText: "বিভাগ",
    mobPopularAreas: "জনপ্রিয় এলাকা",
    mobPopularAreasSub: "লাইভ লিস্টিং দেখতে ট্যাপ করুন",
    mobRecentlyPosted: "সম্প্রতি যোগ হয়েছে",
    mobHomesIn: "এর বাসা",
    mobHomesPostedLast2: "টি বাসা গত ২ দিনে যোগ হয়েছে",
    mobHomePostedLast2: "টি বাসা গত ২ দিনে যোগ হয়েছে",
    mobNoHomesYet: "এই ফিল্টারের জন্য কোনো বাসা পাওয়া যায়নি",
    mobNoHomesDesc: "নতুন কিছু এলে আমরা সাথে সাথে জানাব। ফিল্টার সরিয়ে আরও দেখুন।",
    mobClearFilters: "ফিল্টার সরান",
    mobHavePropertyKicker: "বাড়ি আছে?",
    mobHavePropertyTitle: "৩ মিনিটেই ভাড়া দিন",
    mobHavePropertySub: "আজই ৫০,০০০+ ভেরিফাইড ভাড়াটিয়ার কাছে পৌঁছান।",
    mobEndToEndSecured: "টু-লেট প্রো দ্বারা সুরক্ষিত",
    mobNewToday: "আজ নতুন",
    mobDayAgo: "দিন আগে",
    mobDaysAgo: "দিন আগে",
    mobMonth: "মাস",
    mobBed: "বেড",
    mobBath: "বাথ",
    mobReviews: "রিভিউ",
    mobVerified: "ভেরিফাইড",
    mobApartment: "অ্যাপার্টমেন্ট",
    mobFamilyFlat: "ফ্যামিলি ফ্ল্যাট",
    mobBachelor: "ব্যাচেলর",
    mobStudio: "স্টুডিও",
    mobSublet: "সাবলেট",
    mobStudent: "ছাত্র/ছাত্রী",
    mobPremium: "প্রিমিয়াম",
    mobHot: "হট",
    mobWhatAreYouLookingFor: "আপনি কী খুঁজছেন?",
    rentMenu: "ভাড়া",
    mobRentDesc: "অ্যাপার্টমেন্ট, সাবলেট, ব্যাচেলর ফ্ল্যাট",
    buyMenu: "ক্রয়",
    mobBuyDesc: "বাড়ি, ফ্ল্যাট, জমি",
    commercialMenu: "বাণিজ্যিক",
    mobCommercialDesc: "অফিস, দোকান, রেস্টুরেন্ট",
    NOT_LOGGED_IN: "আপনি লগইন নন। আবার লগইন করুন।",
    NETWORK_ERROR: "নেটওয়ার্ক সমস্যা — পরে আবার চেষ্টা করুন।",
    REQUEST_FAILED: "অনুরোধে সমস্যা হয়েছে।",
    FILE_TOO_LARGE: "ফাইল অনেক বড় (সর্বোচ্চ ৫ MB)।",
    FILE_READ_ERROR: "ফাইল পড়তে সমস্যা।",
    DEMO_LOGIN_DISABLED: "ডেমো লগইন বন্ধ আছে।",
    INVALID_PHONE_NUMBER: "ফোন নম্বর সঠিক নয়। +880 ছাড়া ১০ ডিজিট লিখুন।",
    MISSING_PHONE_NUMBER: "ফোন নম্বর দিন।",
    QUOTA_EXCEEDED: "আজকের SMS লিমিট শেষ। Firebase প্ল্যান বা টেস্ট নম্বর ব্যবহার করুন।",
    CAPTCHA_CHECK_FAILED: "reCAPTCHA চেক ব্যর্থ। পেইজ রিলোড করে আবার চেষ্টা করুন।",
    TOO_MANY_REQUESTS: "অনেক বেশি চেষ্টা। কিছুক্ষণ পরে আবার চেষ্টা করুন।",
    INVALID_OTP: "OTP কোড ভুল হয়েছে।",
    OTP_EXPIRED: "OTP কোড মেয়াদ শেষ। নতুন OTP নিন।",
    RECAPTCHA_SETUP_ERROR: "reCAPTCHA সেটআপে সমস্যা। পেইজ রিলোড করুন।",
    OTP_PROCESS_ERROR: "OTP প্রক্রিয়ায় সমস্যা হয়েছে।",
    UPLOAD_FAILED: "আপলোডে সমস্যা হয়েছে।",
    no_file: "কোনো ফাইল পাওয়া যায়নি।",

    // ── Chat / Call / Notification UI (messaging overhaul) ─────────────────
    chatViewContact: "কন্টাক্ট দেখুন",
    chatMute: "নোটিফিকেশন বন্ধ করুন",
    chatUnmute: "নোটিফিকেশন চালু করুন",
    chatReport: "রিপোর্ট করুন",
    chatBlock: "ব্লক করুন",
    chatUnblock: "আনব্লক করুন",
    chatUnblockShort: "আনব্লক",
    chatYouBlocked: "আপনি ব্লক করেছেন",
    chatCantReply: "এই কন্টাক্টকে মেসেজ পাঠানো যাচ্ছে না।",
    chatActiveNow: "এখন সক্রিয়",
    chatForwarded: "মেসেজ ফরওয়ার্ড করা হয়েছে",
    chatForwardFailed: "ফরওয়ার্ড ব্যর্থ হয়েছে। আবার চেষ্টা করুন।",
    chatDeleteFailed: "মেসেজ ডিলিট করা যায়নি।",
    chatRemovedForYou: "আপনার জন্য সরানো হয়েছে",
    chatCopied: "কপি করা হয়েছে",
    chatPinned: "মেসেজ পিন করা হয়েছে",
    chatUnpinned: "মেসেজ আনপিন করা হয়েছে",
    chatActionFailed: "কাজটি ব্যর্থ হয়েছে। আবার চেষ্টা করুন।",
    chatPinnedLabel: "পিন করা",
    chatUnpin: "আনপিন",
    chatForwardTo: "ফরওয়ার্ড করুন…",
    chatNoForwardTargets: "ফরওয়ার্ড করার মতো অন্য চ্যাট নেই।",
    chatSayHiTo: "হ্যালো বলুন",
    chatAskAnything: "যেকোনো কিছু জিজ্ঞাসা করুন",
    chatTypeMessage: "একটি মেসেজ লিখুন…",
    chatAskAI: "AI অ্যাসিস্ট্যান্টকে যেকোনো কিছু জিজ্ঞাসা করুন…",
    chatMessages: "বার্তা",
    chatCalls: "কল",
    chatChatsTab: "চ্যাট",
    chatCallsTab: "কল",
    chatSearchChats: "চ্যাট খুঁজুন…",
    chatSearchCalls: "কল খুঁজুন…",

    notifTitle: "নোটিফিকেশন",
    notifMarkAllRead: "সব পড়া হিসেবে চিহ্নিত করুন",
    notifClearAll: "সব মুছুন",
    notifEmpty: "সব দেখা হয়ে গেছে।",
    notifRemove: "সরান",
    notifSwipeHint: "সরাতে কার্ডটি বাঁয়ে বা ডানে সোয়াইপ করুন",
    loading: "লোড হচ্ছে…",

    contactInfo: "কন্টাক্ট তথ্য",
    contactCall: "কল",
    contactVideo: "ভিডিও",
    contactProfile: "প্রোফাইল",
    contactSharedMedia: "মিডিয়া, লিংক ও ডকুমেন্ট",
    contactLockPin: "PIN দিয়ে চ্যাট লক করুন",
    contactRemovePin: "PIN লক সরান",
    contactOn: "চালু",
    contactOff: "বন্ধ",
    contactBlockName: "ব্লক করুন",
    contactReportName: "রিপোর্ট করুন",

    mediaTitle: "মিডিয়া, লিংক ও ডকুমেন্ট",
    mediaTabMedia: "মিডিয়া",
    mediaTabLinks: "লিংক",
    mediaTabDocs: "ডকুমেন্ট",
    mediaNoPhotos: "এখনও কোনো ছবি বা ভিডিও নেই।",
    mediaNoLinks: "এখনও কোনো লিংক বা ভয়েস মেসেজ নেই।",
    mediaNoDocs: "এখনও কোনো ডকুমেন্ট বা PDF নেই।",
    mediaVoiceMessages: "ভয়েস মেসেজ",
    mediaLinks: "লিংক",

    msgReply: "রিপ্লাই",
    msgForward: "ফরওয়ার্ড",
    msgCopy: "কপি",
    msgPin: "পিন",
    msgUnpin: "আনপিন",
    msgMute: "মিউট",
    msgUnmute: "আনমিউট",
    msgRemove: "সরান",

    chatDeleteConversation: "কথোপকথন মুছুন",
    chatDeleteConfirm: "এই কথোপকথন মুছে ফেলবেন?",
    chatDelete: "মুছুন",
    chatConversationDeleted: "কথোপকথন মুছে ফেলা হয়েছে",
    attachPhotoVideo: "ছবি ও ভিডিও",
    attachDocument: "ডকুমেন্ট",
    attachTitle: "ছবি, ভিডিও বা PDF যুক্ত করুন",
    notifNewMessage: "নতুন বার্তা",
    quickReplyPlaceholder: "উত্তর দিন…",
    quickReplySent: "উত্তর পাঠানো হয়েছে",

    callRinging: "রিং হচ্ছে…",
    callCalling: "কল করা হচ্ছে…",
    callIncoming: "ইনকামিং কল",
    callVideoCall: "ভিডিও কল",
    callVoiceCall: "ভয়েস কল",
    callMuted: "আপনি মিউট করেছেন",
    callDecline: "প্রত্যাখ্যান",
    callAccept: "গ্রহণ করুন",
    callCancel: "বাতিল",
    callMute: "মিউট",
    callUnmute: "আনমিউট",
    callCamera: "ক্যামেরা",
    callCameraOn: "ক্যামেরা চালু করুন",
    callCameraOff: "ক্যামেরা বন্ধ করুন",
    callEnd: "শেষ",
    callFlip: "ফ্লিপ",
    callFlipCamera: "ক্যামেরা ঘোরান",
    callMissedTitle: "মিসড কল",
    callEndedTitle: "কল শেষ হয়েছে",
    callDeclinedTitle: "কল প্রত্যাখ্যাত",
    callBusyTitle: "কল প্রত্যাখ্যাত",
    callCancelledTitle: "কল বাতিল হয়েছে",
    callFailedTitle: "কল ব্যর্থ হয়েছে",
    callFailedSub: "কলটি সংযোগ করা যায়নি",
    callBackAction: "ফিরতি কল",
    callNoLongerActive: "কলটি আর সক্রিয় নেই",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(readInitialLanguage);

  // Wrap setLanguage so every change is persisted. Components keep calling
  // `setLanguage(name)` exactly like before — no change needed at call sites.
  const setLanguage = (next) => {
    setLanguageState(next);
    if (typeof window !== 'undefined') {
      try { window.localStorage.setItem(LANG_STORAGE_KEY, next); } catch { /* ignore */ }
    }
  };

  // Defensive: if a translation key is missing in the chosen language we
  // fall back to the English value rather than rendering `undefined`.
  const base = translations[language] || translations[DEFAULT_LANGUAGE];
  const fallback = translations['English'];
  const t = new Proxy(base, {
    get(target, prop) {
      const v = target[prop];
      return v !== undefined ? v : fallback[prop];
    },
  });

  // Keep <html lang="…"> in sync so screen readers + Chrome translate UI
  // pick up the language change.
  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language === 'বাংলা' ? 'bn' : 'en';
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
